# (PART) Part 1: Right from the very start {-}


\mainmatter

# Introduction  {#part1}

Right from the very start of your PhD, it is important for you to become familiar with the goal of what you are trying to achieve, how you plan to achieve it, and (believe it or not) what you plan to do afterwards. Both short-term and long-term planning will be one of the [core skills](#coreskills) that are the subject of Part I. You are likely to have had experience of each of these core skills before, but this part of the book tries to show you the importance of growing these skills and having the discipline to apply them regularly to achieve your goal of finishing  your PhD. Some of the most important core skills involve critical reading and regular writing, skills that you will need to begin acquiring and practising from the outset of your studies. Managing your time day-to-day will help you find time to practice these skills alongside your other commitments. There are a lot of things to think about as you start your PhD, and for many of these, it is far easier to make informed decisions from the outset. Preparing yourself for the right mental state will also be very important for your ability to work under pressure. Getting into good habits at the beginning will put you in a commanding position later. This first part of the book aims to help you assess your current position, and realign yourself toward an optimum mindset for doing your PhD in Biological Sciences.
