# What is a scientific journal for? {#whatjournalfor}

It’s worth reflecting on why we have scientific journals, and what they are for. Primarily journals are a means of communication for the academic community. The academic community here should be regarded in the broadest of interpretations. For example, some journals also serve to disseminate research to other those who draw-up and implement policy. Others are aimed at managers who want to base their actions on scientific findings. The direction and inclusivity of the audience is pivotal in both [what](#whattowrite) and how we write.

- Journals record and disseminate the findings of individuals and teams of academics from all over the world. 
- By having a date when they are published, together with the names of the authors, they record primacy; that is who came up with the finding or idea first. Also see important arguments against the need for primacy [@casadevall2012reforming].
- They attempt to register legitimacy by collating and integrating comments and concerns through [peer review](#peerreview).
- Lastly, they archive these findings so that in future people can build on the work. 


There are so many scientists in the world publishing so many papers that it's not possible for all scientists to read everything. Today annual growth in scientific papers is 5.1%, equivalent to a doubling time of 13.8 years [@bornmann2020growth]. Contrast this with the early days when there were only two journals and they published all of the studies that were being undertaken at the time. Over time there has developed a natural hierarchical system of what scientists will read. This is reflected in citations, and the simplest measure of journals is something called the [Impact Factor](#impactfactor). 

It has been said that ‘authorship’ is a relatively modern concept, emerging from the empiricism of England’s middle-ages [see @cronin2001hyperauthorship]. In our recent history, it is considered to be important for individuals to record who thought of what and when. From these authors, we give societal ‘author-ity.’ This gives credit where it's due. In the big scheme of things of course it's not important who did it. We know from historical examples like Darwin's theory of natural selection and Wallace’s very similar thoughts will merely be a product of many people who were thinking about these ideas at the time. Although certain authors may be ‘ahead of their time’, the majority of thoughts and ideas that come around today are a product of their time. However, for individuals and their institutions it can be important to claim credit as this may translate into some monetary value (e.g. with patents) or a prestige value. The regulated system of a taxonomy puts a lot of importance on the priority of who described what and when.

The system of editors and peer reviewers determining whether or not a manuscript possesses sufficient merit to be published is still regarded as the gold standard in science [@mayden2012peer]. As you will discover, it is often a very high bar to achieve. Of course both editors and peer reviewers are human and so the system is not perfect. We'll talk more about peer review in [another chapter](#peerreview). 

Archiving the findings of scientists is perhaps one of the most important roles of publishers that we should be most concerned about. In my career, I have seen the changes from strictly paper dissemination of scientific findings, as it was for the past 350 years, to primarily electronic findings many of which are never printed by the majority of readers. We should be concerned about how long these records will last. If you have never thought about the longevity of data storage, then this is something that you should give some thought to. We all need to change our perspectives on long-term thinking as this impacts almost every societal function (see the [Long Now Foundation](https://longnow.org/)).
