# The scientific project and scientific living {#lifescientific}

Throughout the book, I make reference to the ‘scientific project’ as a greater plan to which our studies in biological sciences is simply a part. I consider the scientific project as a path that humanity should continue to travel in order to reach a higher and more just way of living. Our societies have evolved from places where superstition and belief were the basis for societal rules that favoured the privileged classes. Science is a process in which we reach conclusions based on egalitarian reasoning and evidence, something that we can aspire for the larger community around us. Already, most societies are making the majority of their collective evidence-based decisions through the guidance of science. Therefore, if we consider our knowledge-based societies to be democratic, then all citizens of that society should understand the processes under which the foundation of that knowledge is acquired [@sagan2011demon]. Yet globally, public skepticism in science has been rising, and has reached as high as 35%. To consolidate this growing position of science in society, and the decline in public acceptance, scientists will need to become more open, communicative and seen to be conducting their own profession in a way that reflects these ideals. There is evidence that increasing communication from scientists to the public results in a decrease of skepticism ([see here](https://multimedia.3m.com/mws/media/1898512O/3m-sosi-2020-pandemic-pulse-global-report-pdf.pdf)).

Imagine a world in which all of the principal decisions are made as a result of advances in science, but vanishingly small numbers of people actually understand how science works. This is not a world that we would want, but as Carl Sagan [@sagan2011demon] pointed out, it’s one that could all too easily happen. Therefore, to prevent the workings of science falling into the hands of a minority, we have a duty to communicate our science to the majority. 

Ultimately, what we want from the scientific project is to draw everyone in. That is not to say that there is no place in the world for other subject areas. One of the greatest misadventures in my own education was the indoctrination that I received that there were two streams in education, one for STEM and one for arts. I hope that you managed to escape this narrow minded and factually incorrect view, because as you will discover there are high levels of creativity demanded within the scientific framework, and those who have more talent in communicating their science will likely be more successful in their careers as a result. Moving forward with the scientific project does not mean that everyone must become a scientist, but instead that the process by which scientists establish knowledge is understood. Indeed, as we shall see (below), sceptical thinking, as exemplified in science, is a healthy way for everyone in society to avoid time wasting and potentially being deceived or conned. It is also vital that the scientific process be transparent in a way that results can be understood and therefore respected. 

Here I provide an example of the way in which there is a need for efficient communication between biological sciences and civic society: 

## Example: Invasive species 
Alien species are those that have been moved by human agents across biogeographic barriers into parts of the world where they did not evolve. Once these aliens arrive in their new environment, some reproduce and become established, and after a lag, a fraction of these spread, and become invasive, often with substantial impacts on the environment and the socio-economic efforts of people in those invaded areas. Invasive species disproportionately affect poorer people in our society, often completely disassociated with the pathways responsible for the introduction and spread. Removing invasive species requires a considerable amount of effort, and unless this is supplied by taxpayers, via governmental policy, falls on those directly impacted. Invasion science, the expanded transdisciplinary area stemming from invasion biology, is required to engage with all stakeholders in invasions, and most importantly to prevent new invasions. Because introductions are made by humans there is a critical need to communicate with those stakeholders along introduction pathways.

For existing invasions, social scientists and economists are needed to determine their impacts on people in invaded areas and determine how to best alleviate the invasion or mitigate its effects without it moving further and impacting more communities. Biological scientists need to assess the impact on the environment, and investigate ways in which the species can be removed, their spread curtailed, or their impacts neutralised. Importantly, the results need to be discussed with all stakeholders to achieve a desirable outcome for those impacted most. Invasions at larger scales will normally require governmental resources to ensure that communities can continue to function, especially to best deliver their services to the society. Governments require evidence-based decisions that are reached from well-researched studies conducted in the field. Effective measures may necessitate large sums of money, and governments require that this process be transparent so that the taxpayers’ money they are investing is spent efficiently. 

We know enough about invasive species to be aware that there are greater threats to society from species that have not yet arrived than those already present. This means that all societies need to guard against the threat of potential future invasions, and still maintain the trade that brings needed goods into their areas. Most societies have no checks in place, but the immediate need to prevent new invasions, and halt the effects of existing ones, is recognised on a global scale. Biologists have an important role to play as key agents in informing society on the impacts (especially when they disproportionately impact those least privileged in society), pathways, removal and prevention of invasive species. Failure to effectively communicate with any of the stakeholders along the invasion pathway will result in more propagules arriving, and with them the increased chance of more species becoming established and eventually invasive. 

In the case of biological invasions, communication needs first to flow from the various stakeholders to direct the research needed. The solutions required are context specific, and the lessons learned need to be communicated back to the stakeholders, including governmental policy makers, in the form they require to action the findings. Ineffective communication from scientists to the stakeholders may result in solutions being ignored or misinterpreted. Documentation disseminated to the global scientific community, through scientific publications, is needed in case it may help the response of other societies with similar problems. 

## Should society lead the sciences or sciences lead society? 
Of course, the answer is simply that there must be feedback between science and society. As science advances, society learns of these advances and views are advanced. To become incorporated as a societal norm takes time. Over time, views from science that appear radical to society become mainstream and accepted. Think of the views on the earth being round, or more recently, the general acceptance that the universe started with the ‘big bang’. The counterculture, also known as post-truth, faction in society that espouses views accepted by the mainstream and proved by science beyond reasonable doubt is not a novel phenomenon. Indeed, in the scientific project, we need to accept that these views will persist and empower the general populace to understand why and how they can be shown to be false. Hence, your view that the earth is not flat is bolstered if you can provide three ways to demonstrate this as fact (pick the ones you like from 7 listed [here](http://crosstalk.cell.com/blog/seven-ways-to-prove-earth-is-round) or [here](https://www.unlv.edu/news/release/round-earth-clues-how-science-proves-our-home-globe)). Otherwise, your assertion that it is not flat will appear as easily denied as a ‘flat-earther’s’ assertion that it is. Thus the power of the scientific argument in society is that it is not simply contradiction or gainsay but that there is evidence. 

The scientific project is currently not the open virtuous eutopia that we would like. Indeed, as scientists are humans and part of the current society, they are prone to the same trappings of wielding power and influence in order to get ahead. As you get toward the end of this book, you will see me calling out increasing parts of the scientific project that are currently riddled with bias, thereby weakening the entire process and disenfranchising the most vulnerable. Reforming science is no easy task. Reforms are needed throughout the structures that fund, employ and disseminate scientific research. Sweeping this all away will take a concerted effort but might well be easier in science than in other sectors of society. Nearly all scientists recognise that science needs to be objective and impartial in order to succeed. Their objectivity makes them an ideal group to kickstart a fairer, more transparent and open system. As you will see, there has already been a move to make science more open, and by embracing this transparency the next generation of scientists will reap the benefits, and be on a sounder footing to improve a better scientific society. 

## Carl Sagan’s “Baloney detection kit” 

or __"How to know when what you smell is bullshit"__

In his book, Demon-Haunted World, Carl Sagan [-@sagan2011demon] provides his take on how science provides scientists with what he terms ‘Baloney Detection’, commonly referred to today as ‘bullshit’. These are well worth recording here as they provide a guiding light for all scientists whether they be novices, emerging or established. They are also easily taught and the foundation of what we should spread in the Scientific Project. 

As humans, we are all susceptible to bullshit, hoaxes, charlatans and contrived deceptions as they are often more appealing than the truth. However, science is about truth-seeking, and by applying a set of simple rules, Sagan argues, we can avoid being misled or distracted by ideas that may waste our time and energy by using ‘skeptical thinking’. These rules are useful in your scientific life when considering hypotheses or when building arguments to explain your results. However, as Sagan argues, these simple rules are also useful in your day to day life, and as a simplified example of the scientific method, we can pass them onto all our fellow citizens. 

1. You should always seek independent confirmation of results. 
1. Seek out different opinions on the results and consider all possibilities.
1. Don’t believe facts simply because they are spoken by an authority on the subject. We know that humans are prone to [confirmation bias](#TypeI), and often exhibit motivated reasoning, especially if they have some vested interest. Even the most experienced have made mistakes in the past and will again in the future. My preferred way of thinking of this rule is to acknowledge that experts are made of ex- (a has been) and -spurt (a drip under pressure).
1. [Use a hypothetical deductive framework](#hypothesis). Instead of accepting the first (hypothesis) explanation, think of all the possible reasons why a result might have occurred and then consider how you could (or perhaps you already have in your experiment) disproved each one. You may find that an untested hypothesis to explain the results represents a major caveat that could be tested, or can’t yet be tested. Either way, you need to remain open to the possibility that this explains your results. This leads neatly onto:
1. Don’t get too involved with keeping your chosen hypothesis [opening you to potential cofirmation bias](#TypeI). Remain critical to the possibility that it might be wrong, and provide ideas on how to substantiate or disprove competing hypotheses. If you don’t, others will. 
1. If at all possible, use a quantitative method to test your hypothesis. You should already be well on the way to this one inside your PhD, but it is worth bearing in mind especially when it comes to considering testing other competing hypotheses. How could they be quantitatively tested?
1. Arguments ([as we see later](#argument)) consist of a chain of statements that follow one from the other. This chain is only as strong as its weakest link, and the strength of each link in the chain (your argumentative statements) must be critically considered by you. 
1. [Occam’s Razor](#argument) dictates that given two hypotheses that equally explain the results, the simpler one is likely more plausible. Or put another way, the more links you have in your chain, the more likely that one of them is not as strong as you would like it to be.
1. Your [hypothesis](#hypothesis) (or argument) must always be falsifiable. That is, that your test should be able to find that it is incorrect. If your test cannot show that your hypothesis is incorrect, then it isn’t worth much. 

Sagan provides plenty of real-world examples of each of these arguments, and I’d suggest that you consult his book [@sagan2011demon] if you are interested in following these up. Similar approaches, but written in different styles, are provided by Richard Dawkins in his [-@dawkins2004devil] book: A Devil’s Chaplain, and Julia Galef in her [-@galef2021scout] book: The Scout Mindset. 

## Live your life scientific
>__“Science is more than a body of knowledge, it is a way of thinking”__
>Carl Sagan [-@sagan2011demon]

I would encourage you not to stop your objective and evidence-based thinking when you leave the office or laboratory. By applying the rules of science to other sectors of society, you will find that there are many societal norms that could benefit from similar reform. Certainly, a lot of the technology developed through scientific inquiry can be used to help society reform, but scientific thinking will help everyone. As well as bringing the world to scientific thinking, as scientists we should take scientific thinking to the world. 

## Citizen science
For a long time, I struggled with the term 'citizen science' as I reasoned that many such ventures did not involve citizens doing science. To me, most seemed focussed on outsourcing large tasks to willing public participants: i.e. having citizens do some grunt work. Collecting data or doing a fraction of the analysis is not science. However, in light of the scientific project, I have changed my mind. All of these projects offer citizens a way to participate in scientific projects in a way that was previously unavailable to them. They promote direct communication between scientists and citizens. In this way, they serve to promote the understanding of science to the general public.

One aspect of this will be to bring more of the population into conducting scientific studies. This can be at the level of funding scientific studies. Crowdsourced scientific studies promote communication between the scientists and the funders to a level that is meaningful to both groups, such that they make up a large scale collaborative research interaction [@uhlmann2019scientific]. Citizen science contributions mean that the collection of data can be shared on a much broader scale, than would be traditionally possible. Of particular interest in the biological sciences is the identification and collection of locality data for biological species (on platforms such as iNaturalist). But increasing numbers of projects are demonstrating novel ways for the public to increasingly participate meaningfully in scientific endeavour [@bonney2014next; @silvertown2009new]. Science is a joyful and spiritual experience for most of us that participate in it. There’s no reason not to spread that joy as widely as possible. 
