# A healthy body to go with your PhD mind {#healthy}

While I’m busy handing out advice, here’s some of the best that I have to offer. If you don’t do it already, then when you start your PhD start regular exercise. There’s an old adage that ‘a healthy body leads to a healthy mind’. I never gave it much attention until I started exercising regularly some 7 years ago. Getting fit was the best thing I ever did to improve my work.

## Being physically active improves concentration

The first thing I found was that I could sit and concentrate on work for longer. Before I got fit, I was constantly distracted and needed to take lots of breaks. Now I find that my concentration is much better and that as my fitness stamina increases, so too does my ability to concentrate. 

## Time to think

I used to think that the time I spent exercising was unproductive with respect to work. Now I have begun to realise that this represents some of my best thinking time. I use the time I spend trail running to turn ideas over in my head and especially to think through the logic in arguments, and potential flaws in experimental design. This isn’t to say that I don’t need to put time in at the computer writing it all down, or talking through ideas with colleagues. But I find the meditative time I spend exercising to be especially productive. 

## Balancing work with life

Having already told you that doing a PhD might unbalance you mentally, regular exercise is a really good way to make sure that you retain that balance with life [see @hotaling2018publishing]. By life, I'm referring to everything away from your academic work. This might include, family, friends, sport, hobbies (even fishing). If you don't have friends outside your academic life, then it would be a good idea to find some so that you can keep in contact with the 'real world'.

If you already exercise, then you likely know how important this is. But if you don’t then my best advice (above anything else that you might read in this book) is to start as soon as you can. Do whatever is right for you. If you don’t already know, then try out different clubs or activities at your institution. There are normally lots to choose from. Make sure that you schedule regular time for your activity, even if that means that you run in the mornings before field work starts, or you spend your evenings doing tai-chi on the beach after a day at sea doing research on dolphins. Take your exercise with you wherever you go for your studies. Take it as seriously as you do your studies and you’ll find that both will benefit. 

Once you have a healthy body, you’ll find that there are all sorts of things that go along with this. The desire to fill it with healthy food resulted, and this later tied in with my interest in the gut microbiome. I now have many fermented foods in my kitchen (much to the horror of my kids), and the improvement of my digestive system. I could go on, but I’ll spare you. Instead, I just want to emphasise that I consider that not only will your quality of life improve, but so will your work if you include regular exercise as part of your PhD regimen.
