# When should you be an author? {#authors}

Who should be an author is being increasingly regulated because of widespread abuse, including ‘honorary authors’ or excluding ‘ghost authors’. Back in the day there were people that used to add fictitious characters to their author line (including their dogs!) as a joke. These days we have such a thing as [ORCID](#orcid) that attempts to register all authors, turning them into numbers ([see Part III](#orcid)). One of the benefits with the ORCID system is that you can have your name the way you want to have it, even if it is not a standard western style surname [@goyesvallejos2021what]. The need for all this regulation is because publications have turned into a kind of currency for academics. And when there is currency involved, abuse quickly results in human systems followed by the need for regulation. Hence, one of the results of going transparent is that we all become registered numbers (and our dogs won't get authorship any more). Perhaps this is just the loss of an age of innocence, at least on the part of our dogs!

A lot of the literature on the subject of ghost and honorary authorships has come from the medical profession, perhaps as this profession is prone to ghost authorship via the pharmaceutical industry [@matheson2016ghostwriting], and honorary authorship from heads of large research groups [see @rennie1994authorship].

## Ghost authorship {#ghost}
Ghost authorship is when people, not included in the author line, have contributed substantially to the study [@matheson2016ghostwriting]. Note that ghostwriting outside science is usually when someone who has the talent to write, writes the ideas of someone who doesn’t for a fee, and in return the latter takes the author line. These are called "paper mills" and they are discussed in [Part I](#papermills)).

There are many potential sources for ghost authors, including past students whose thesis work is taken by unscrupulous advisors, and published without their inclusion. More commonly, I believe, is that those who contribute substantially are not included as authors for political reasons (they have fallen out of favour with those who are the authors), or they are simply forgotten because they have moved away from the institution. Ghost authorship is a land of the disenfranchised. This is becoming increasingly prevalent in the world of contributions of data, which is also freely accessible. Some authors will take and use the data, only referencing the DOI for where they obtained it. Others will include the original people who created the data as authors because they value their continued insight and input. Where the situation becomes very messy is when some people are included and others are excluded. This is my experience where a paper simultaneously contains [honorary authors](#honorary) and excludes ghost authors. A study by Wisler et al. [-@wislar2011honorary] found ghost authorship in medical publications at 7.9%, although I’d argue that their methods (contacting corresponding authors) mean that the real levels are likely much higher.

While the world of inclusion (see below) has a warm and friendly glow about it (everyone appears to benefit), exclusion is characterised by lack of information, contact and reasoning. If you are excluded from a publication even when you have contributed, you will not be getting an email from the authors detailing their decision. You’ll be lucky if they even send you a copy once it’s published. Meanwhile, those who are included will remain in the loop.

### Paper mills {#papermills}
The concept of a paper mill is rather different from [ghost authors](#ghost) or even salami-slicing ([Part IV](#salami)). Paper mills involve third parties, often not included on the author line, producing material for publication from scratch: i.e. companies that specialise in producing content that will pass peer review for those who want to buy authorship. The world of paper mills is particularly shady and it is not clear what sums of money are exchanged for these types of goods. What we do know is that there are benefits to those who are put on the authorline, while those that produce the manuscripts generally rewrite text and pull protocols from manuscripts that are already published. Results are often images that have already been published and/or are manipulated to suit the content (see [Part IV](#fabrication)). Hence, paper mills are a systematic and deliberate manipulation of the publication process [see @teixeiradasilva2021abuse]. 

## Honorary authorship {#honorary}
Honorary authorship happens when people who have not contributed meaningfully to a study are included in the author line. If publications are the currency of science then you can see how being added to other people's publications increases your apparent productivity. While this might sound surprising to you, you should know that does happen and might be more common than you think. The Wisler et al. [-@wislar2011honorary] study found that honorary authorship was as high as 17.6% in medical publications. It’s worth noting that this may vary between disciplines as there are various traditions in some disciplines whereby the head of a large team may always be included as an author of a paper that emerges from the team, whether or not they were involved. In biological sciences, teams tend to be quite small with a single or rarely multiple Principal Investigators (PIs). This means that your PI will likely be directly involved with your research and therefore also an author. Imagine a very large team with multiple PIs working under a head who insists that they are an author on every publication. This could add up to hundreds of publications in a year (e.g. [Yuri T. Struchkov is currently credited with >1600 publications on Scopus](https://www-scopus-com.ez.sun.ac.za/authid/detail.uri?authorId=35427689100)), and such prolific authorship has been questioned [e.g. @rennie1994authorship]. However, there appear to be very different levels of what could be considered credible and what incredible [e.g. 25 papers a year: @wager2015too], and I respond to this, and the general question of how prolific authors are becoming, [later](#publishmore).

In the biological sciences, the area of molecular phylogenetics has traditionally honoured those who collect tissue samples with authorship on the resulting phylogenies when published. As I mentioned above, this is not always equal and has also been used to politically [honour](#honorary) or [ghost](#ghost). The reason given for honouring contributors in this way is that the studies could not have been done without the tissues. On the other side, some people have long lists of publications based on tissue donations and very little else. 

## A need for transparency - DORA {#DORA}
Given the problems with both ghost and honorary authorship, there is clearly a need for transparency about who the authors are and what they have actually contributed. This was recognised by the [Declaration of Research Assessment](DORA: https://sfdora.org/), which has a growing number of signatories as well as some solid ideas on the way forward in assessment of research and researchers. In particular, DORA is against the use of Impact Factors ([see below](#impactfactors)) and other journal based metrics, and instead assesses the research on its own merits. DORA also encourages everyone to embrace the opportunities offered by online publication, including colour figures and unencumbered word lengths. DORA also encourages specific information to be published about individual author contributions. In short, DORA stands for transparency and it would be worth you looking at their statement and finding out whether your institution is a signatory.

There are no universal rules about what or how much you should contribute in order to become an author of a scientific paper. However, some journals are independently initiating their own standards, and this might become mainstream. Thus, it is worth discussing the criteria for being an author with your advisor preferably in a lab meeting so that everyone knows where they stand. there's a chance that your thesis chapters (when they are published) will be authored only by you and your advisor. But this can become much more complicated if you collaborate with more people in order to do the work. In turn you may (or may not) be invited onto their papers as an author. Confused? Then let’s look at this more closely.

## Who should be an author?
There is an increasing number of journals that now give clear instructions on who qualifies as author on a paper, and these have been formalised by the International Committee of Medical Journal Editors (ICMJE), and this area has been rapidly evolving [@baskin2011honorary]. Although these approaches are clearly made to prevent [honorary authorships](#honorary), it is hard to see how they help include [ghosted authors](#ghost). Scientists are notorious in their abilities to make _post hoc_ rationalisations. 
As an early career researcher, I'd suggest that you use questions around authorship as a way to formulate how participating researchers fit into the study. By openly attributing roles to a checklist, everyone buys into what is expected of them. Any additions to this author line-up should be openly discussed amongst all authors, and attibuted to the checklist, as the project proceeds. 


### Rescognito, ORCID and the CRediT Contributor Checklist {#rescognito}
A new initiative under the name [Rescognito](https://rescognito.com/) has teamed up with [ORCID](#ORCID) to formally list the ways in which researchers are recognised per publication. Rescognito maintains the Data Availability Checklist, Contributor CRediT Checklist and Funder Information Checklist. 

The [CRediT Contributor Checklist](http://credit.niso.org/) contains 14 fields:

Conceptualisation       Data curation       Formal Analysis       Funding acquisition       Investigation       Methodology       Project administration        Resources       Software          Supervision       Validation        Visualisation       Writing – original draft          Writing – review and editing

Visit their website to learn more about these fields. This area has new initiatives and registries opening up. We will see how many journals adopt these and what becomes of existing initiatives in the future.

### If you suspect irregularities in authorship

The [Committee on Publication Ethics](https://publicationethics.org/) (COPE) has published a useful flowchart to guide researchers on [how to recognise potential authorship problems](https://publicationethics.org/resources/flowcharts/how-recognise-potential-authorship-problems) [@cope2018how]. Or more specifically, how to recognise [ghost, guest, or gift authorship in a submitted manuscript](https://publicationethics.org/resources/flowcharts-new/changes-authorship) [@wager2006suspectedb].
