# Regular writing {#regularwriting}

This book is about writing your PhD in Biological Sciences. This chapter is about using regular writing as a core skill to improve your writing skills throughout the duration of your PhD studies. Writing is a [core skill](#) that you need to work on, and a regular writing slot is the best way to develop this skill. This chapter will be short because, unlike the other core skills in this section of the book, the rest of the book will go into scientific writing in detail and provide you with all the advice you need to get started writing.

Just like any skill, you can't expect that scientific writing is going to come easily to you, and you need to invest time not only to learn how to do it (Parts [II](#partII) and [III](#partIII)), but also to practice writing so that you implement the skills that you learn on a daily basis. Regular writing and implementing what you learn in this book will be the best way to improve your scientific writing skills. 

## Write every day

When you make your [day-to-day](#day-plan) calendar for your normal working week, I strongly suggest that you put a 40 minute block every day that you dedicate to scientific writing (i.e. thesis writing). Know what topic you are going to write about before you start, and make sure that you have already conducted the relevant [critical reading](#critical) to accomplish this. Start your 40 minute block by writing the [outline](#outline) of your work with a list of relevant papers to cite. Then concentrate for these 40 minutes on writing something that meets the goal you set.

You need to be realistic about what you can achieve in 40 minutes. Especially at the start of your PhD, you might not be able to write more than a few sentences or a paragraph in 40 minutes. At the very beginning you might even struggle to complete your [outline](#outline). However, the discipline of dedicating 40 minutes every day to undistracted writing will pay-off over time.  

Don't expect perfection in these 40 minute sessions. Instead, concentrate on your plan and think about how to introduce ([topic sentence](#paragraph)), and [logically link](#argument) sentences that are backed up with [citations](#citations). The first paragraph that you write may not be a keeper, but making that start is important as it will show you what you need to change. 

Build on your paragraph, but don't return to the same paragraph every day. It is important to change the writing topic often enough so that you don't get stuck on a particularly difficult task. By changing the topic several times during your week, you'll should find that it retains your interest. You can add plan in weeks to come to return to tasks that you are struggling with or which need more time to complete.

While I recommend that you write every day, I would stress that this means every working day. You should have a break for at least one day a week. You should also have some days every year when you have a holiday and others where you are doing other tasks, like fieldwork, that will preclude you from writing every day.


### Remember your critical reading

Daily writing will go hand-in-hand with daily [critical reading](#critical). Plan both of these activities in a complimentary way so that you have the reading foundation for what you plan to write. However, make sure that you mix it up so that you get some variety in what you are reading. 

### Reflection {#reflection}

Once you start writing regularly, you will find that you have ideas about how to solve writing problems and ideas about what to cite at other times during your day. Keep a 'writing notes' file or a page in your notebook where you can jot down these ideas, and come back to them in your regular writing time-slot. 

As stressed in the chapter on [health](#healthy), [time spent thinking](#time-to-think) and reflecting on many aspects of your PhD is very important. During your sleeping hours your brain will make connections between items and tasks that you have conducted during the day. Hence, it may be that it may be a only day or two later that connections become clear to you. These insights can be very valuable, so make sure that you keep a note of them and look into them further to see whether they are worthy or important. Remember that your brain can also make false connections, so not every idea will be a winner.

### Use one of the best time-slots

When planning your regular writing, use one of the time slots when you know that your [concentration will be at its best](#day-plan). Don't use a time when you know that you are likely to be tired or unfocussed. The idea here is to maximise your ability to write, during these time-slots. In time, you may well find that as your writing becomes better you will need to dedicate the best time-slots to other priority tasks. But when you start, I'd advise you to begin by keeping the best time-slots for daily writing tasks and [critical reading](#critical).

### When you haven't read enough

At first you will not have read enough papers to properly plan or cite all the relevant literature for the paragraph that you aim. In these first few weeks, concentrate on some of the writing techniques that you are reading about (in this book and elsewhere) so that you get some practical experience of writing some logical sentences, writing hypotheses, etc. The point of making this daily practice in writing is to get yourself used to writing in a scientific way. You can start this from day one, only having read a few of the chapters from this book, so give it a go.

## Be disciplined

Make sure that the 40 minutes you have allocated to writing are spent doing writing tasks. If you fill your 40 minutes with reading, arranging your chair, screen, table then you won't be helping yourself. Especially if you reinforce this by rewarding yourself it will actually cement these [displacement activities](#displacement) instead of rewarding being productive. It will be up to you to decide whether or not you have achieved your goals. 

