# Writing your cover letter {#letter}

Many journals require that you write a cover letter to the editor on submission. Each journal should tell you what this letter should contain. This will vary from journal to journal as some may have a set of check boxes that cover some points in their editorial management software, while others may want a written declaration. It is very important that your letter contains all of the information required by the journal. If not, it could lead to an automated [desk rejection](#desk).

Some journals have a text box in their submission software for you to paste the text of this letter. If there is a text box, then I suggest that you do not compose it on the fly, but plan it out and write it in a word processor so that you can catch any silly spelling or grammatical errors. Others journals might expect you to upload a pdf letter on headed paper from your institution. Make sure you know what is required and that you are prepared. The reason for a formal signed letter on headed paper is that in some submissions, this letter is used as a legal declaration. 

Your cover letter is a professional, formal letter, and should be written as such. Use the conventional letter writing format, including addresses, date, signature, etc. If you are unsure what this looks like, there is some great advice on the web, including templates to use (see [here](https://wordvice.com/journal-submission-cover-letter/) and [here](https://www.springer.com/gp/authors-editors/authorandreviewertutorials/submitting-to-a-journal-and-peer-review/cover-letters/10285574)).

Address your letter to the journal editor. One of the nice things about academic titles is that they are gender neutral, so use them: **Dear Dr. Jones**, or **Dear Prof. Smith**. Even if this person has an office down the hall and you see them every day, keep the cover letter professional. It will go on file with the publisher.

The following points should be covered (where relevant) in the order given as a default. Any content and style requests from the journal, about how the cover letter should be written, clearly takes precedent.


1. The title of your manuscript, the type of submission (review, research article, letter, etc.) and the name of the journal that you are submitting to. Note that it is all too easy to forget to change the journal name when you are submitting to another journal. In my time as editor, I've seen some very nice letters explaining how the manuscript is appropriate to a completely different journal. Not a good start!

1. Statement that your manuscript has not been published or submitted elsewhere, and that all authors have approved the submission. There are other statements that are required by certain journals, and sometimes the journal requests that you copy and paste their text as the cover letter is kept and used as a legal declaration. Also it may include information about ethics clearance and any permits required having been obtained and available should the paper be accepted. Note that you don't need to include all of this information unless the journal that you are submitting to requires it.

1. Include information about why your research is suitable to the [scope](#scope) the journal that you have submitted it to. This requires you to have checked the scope of the journal itself and have thought about exactly how your paper aligns to this. Bear in mind that this is a real problem. Editors get far too many papers that do not fit the scope of their journal, and it takes time to process and reject these (so they are not appreciated). 

1. Novel and innovative research. For journals where the [impact factor](#impactfactor) is important, you may want to emphasise what is novel about your study, and therefore deserving of the impact.

1. Important information that the editor must know. For example, if the manuscript was previously rejected with an invitation to resubmit (then also include the manuscript number that it was given previously). Or (rarely) if you (or others) have previously retracted a similar study, with reasons why this manuscript is not affected. 

1. Connections to other ongoing research. If relevant, state what other manuscripts are already submitted to this or other journals. For example, is your work part of an ongoing consortium or research programme?  The idea here is to demonstrate to the editor that your manuscript [will be cited](#citations) in a timely manor.

1. A final brief statement to the effect that: **"We declare that we have no conflicts of interest."**



## Do editors read cover letters? 

This is a moot point in that you will never know. Some editors definitely read every cover letter [@kenar2016dear]. Even new journals have retained the need for a cover letter when they have stripped down the submission process to a minimum (e.g. _eLife_), and so my suggestion is that it is needed and, hopefully, it will be read. However, every editor at every journal is likely to have their own method of what they regard as important to read [@moustafa2015does], with many actively trying to [minimise this](#editors). Where there are legal requirements, it's not likely that editors will read them, but editorial managers may well make sure that these are present in order not to get a pre-review ([desk](#desk)) rejection. 

Chief editors may read parts of the cover letter along with the abstract before deciding which Associate Editor should be assigned. Some chief editors will even leave this to the Associate Editor. The Associate Editor should read your cover letter in full, together with the metadata and other salient information therein. They should also [read the entire manuscript](#editors). 


## What not to do in your cover letter

- Try not to make your cover letter too long. A single page should be enough to cover all of the points above.
- Don't copy and paste your abstract. There will be a place for this in the metadata on the submissions site. 
- Avoid specialist terms that the editor may not know.
- Don't try and oversell your study, or make excessive claims. 
- Avoid "first ever" claims, as they won't impress the editor.
- Don't suggest potential reviewers unless the journal rubric specifically requests this in the cover letter.
- Similarly, don't suggest people that you don't want to review your article, or start any history of why your submission is complicated by third parties. 
- Don't deviate from a formal letter style.
- Don't have spelling and grammatical errors.
- Avoid formatting the letter in a way that might make it difficult to read: 
  + Don't be tempted to reduce font size to get more in (keep to Ariel 11 point)
  + If you need more space to keep your letter to 1 page, change the margin sizes
  + Don't fully justify text (left justify only)
  + If you are recycling your letter, check that you have changed **everything**.
