# What happens if you don’t have a hypothesis? {#nohypothesis}

So far, we have concentrated on thesis chapters or manuscripts that have [hypotheses](#hypothesis) to test. I have emphasised that there is a need to focus all of the sections of your writing to help frame and understand the hypothesis (in the [Introduction](#introduction)), explain your approach in collecting and testing the variables (in the [Materials and Methods](#methods)), provide the results of your tests (in the [Results](#results)), and respond to the hypothesis (in the [Discussion](#discussion)) together with placing it in the context of other work. But what if you don’t have a hypothesis to test?

There are lots of reasons why manuscripts don’t have hypotheses, and the chances are that in a PhD thesis (for example) you will have at least one chapter where there isn’t a hypothesis tested. It's also possible that you won't have any hypotheses tested, and this is the approach in some disciplines. So, given all the emphasis above, what can be done?

## Is having a hypothesis the gold standard? 

The [hypo-deductive method](#whathypothesis) is certainly a powerful one to use in science but, no matter what you have read or been taught elsewhere, it is not the only scientific approach. Much of what we do in science comes from observational work, and these observations are usually the basis for many of the hypotheses that we pose. But some disciplines are entirely based on observations, and this does not make them obsolete or unscientific. Such disciplines simply don't lend themselves to experimentation, and without an experiment it is hard to control and hypothesise. But we should not confine ourselves to an entirely experimental approach. Here are some reasons why using non-experimental approaches will benefit our science:

1. Observational science (something that I refer to elsewhere as [Natural History Observations](https://howtopublishscience.org/whattowrite.html#natural-history-observations)) can teach us a lot more about systems and inspire greater creativity in our work than plodding from experiment to experiment. 
1. We can infer patterns from process. As humans, we are evolutionarily programmed to see patterns (even when they aren't there) and recognise patterns in the world around us [e.g., @linhares2013what]. It would be crazy to put this ability aside and ignore it when conducting science. Clearly, we are also able to make mistakes when we infer patterns from processes, but this does not mean that it should not be done. But we need to engage in a much more cautious manner when using this approach, always being aware of our bias towards certain explanations so that we encompass others. I would also argue here that this is instrumental in forming hypotheses to test experimentally or in models. 
1. Models of systems are powerful tools to test questions. Models are always simplified versions of complex biological systems, but their power as tools in our scientific approach should no longer be questioned. 

Indeed, there are many shortcomings to using a hypo-deductive approach, as we have seen in the [previous chapter](#TypeI). By allowing ourselves a liberal approach to science methodology we are far more likely to make new connections and infer novel patterns about biological processes. We are more able to be inclusive of different disciplines. It is likely to be advantageous to be open to these diversity of approaches in others' research, just as you should in your own approach.

## Why am I always banging on about hypotheses?
Throughout this book (and in [other books](https://howtopublishscience.org/)) I constantly refer to hypotheses and how important they are when writing your thesis chapters. Why do I do this when I am clearly so positive about using other methods? In many respects, this comes from my attempt to simplify. In most cases, you could replace the word "hypothesis" with "central problematic" and get the same effect. You could also replace some instances with "aim" or "objective" (but not all). There are some points that are unique to hypotheses, and that's why I made my choice about referring to these as they are, generally speaking, the most complex of these alternative approaches. I reason that if you can understand how to approach writing to respond to hypotheses, then you can turn this same approach to your own needs. Add to this that most people, scientists included, misunderstand hypotheses, so there is a need to discuss them and their uses more. 

If you are a biological scientist that does not use hypotheses, then this does not make you inferior, and I hope that you will still find this book useful. If this is you, then let me apologise here and suggest that you mentally shift whenever you read "hypothesis" to the alternative approach that you prefer. 

## Central problematic
If you have a particular problem that your research is trying to solve, this may result in a new methodology or perspective rather than testing a hypothesis. This work is still suitable for a journal manuscript (and there are specific journals dedicated to new methodologies). Instead of introducing your hypothesis, you can simply introduce the problem that your methodology applies to. A new methodology will probably best fill an existing gap, and so your introduction will likely point out what this gap is, provide evidence for why existing methodologies don’t fill the gap, and outline the variables in your novel approach. 

Similarly, if you have a question but not a hypothesis, that your research tries to answer, you can take exactly the same approach to introduce your question. 

Hence, no matter what your central problem is, you still need to identify this and put it at the heart of your manuscript so that all of your sections address this point. Of course, there may be more than one, and if so, you will need to clearly articulate each one and explain how they are related to each other. If you are unsure about how to move forward, the best thing to do is to look to the literature for other examples of what you’re trying to do. Someone has very likely done something similar before. Don’t forget to chat about it with your advisor, as they may have ideas about where to look.

## Does it matter that you don’t have a hypothesis?
Proponents of the hypothetico-deductive method will argue that having a hypothesis makes your work stronger than if you only have a question or prediction. In each case, while your results might help answer your question or confirm your prediction, they won’t test the mechanism (so that you can’t explain why you have the results that you do), and they may not be falsifiable/refutable. Of course, Popper would argue that if you don’t have a null hypothesis, then your methodology isn’t scientific. 


## Avoid HARKing 
There is one very important aspect of your approach whether or not you have a hypothesis, and that is that you know exactly what your study aims are before you start. It is essential for you to frame the context of your study. The central reason why you are conducting the study will lie at the heart of the manuscript, once you've started writing. In the formulaic approach (see [Part III](#formula)), it will be verbalised at the end of the [introduction](#introduction). All parts of the [methodology](#methods) will explain how you approached this central aim. So if you feel that you still don't know what the objective of a certain chapter is, then make sure you discuss it with your advisor so that you know before you start.

Hypothesising After Results are Known (HARKing) is the practice of creating your hypothesis once the results are in and you’ve done some preliminary data analyses to see what is significant [@forstmeier2017detecting]. HARKing has become prevalent in science because of the confirmation bias by journals (only accepting papers that can statistically accept the alternative hypothesis), especially those with higher impact factor. Increasing chances of confirmation bias, or a [Type I error](#TypeI), is not desirable as you are more likely to accept the alternative hypothesis when it is not correct. Alternatively, you should seriously consider [preregistering your aims](#transparency) to remain transparent.
