# Suggesting reviewers {#suggestreviewers}

You will often be asked to suggest reviewers as you submit your manuscript. This can be part of your [cover letter](#letter), or data that you need to fill in during the submission process. Keep in mind that supplying a name alone will not be considered sufficient, you will need their name, the name of their institution and their email address. Some journals will not accept addresses that do not come from institutions unless they can be verified. The reason for this is that there has been an outbreak of fraudulent reviewers, where authors suggested fake reviewers or gave email addresses that they manufactured [see @brainard2018what]. 

In keeping with the [spirit of peer review](#spirit), you should suggest people that you think will provide insightful reviews. These could be people that work in the same area (but that aren't involved in your study). Personally, I would be likely to name the same set of people that I would invite myself if I were editing. People that I believe would provide a constructive and unbiased review. 

## Who should you not suggest?

 - Anyone who is an author or in the acknowledgements
 - Anyone else you feel may have a conflict of interest 
   + connected with the work but not an author
   + someone who was on your review committee
 - Someone in your department or even at your institution (there may be exceptions here, but often journals will not consider people with matching institutional emails)
 - friends, labmates or even relatives (even if you genuinely think that they would do a good job)
 - people who are regular co-authors (grant panels specifically ban you from naming these people as potential reviewers. If you have a large network, this can be problematic)
 
## Who should you oppose?

In addition to allowing you to suggest reviewers, many journals allow you to oppose reviewers. I usually leave this blank. If you have a particular lab or persons who you know will not follow the [spirit of peer review](#spirit), you could enter them here. 
 
 
## Who will the editor use?
It is worth bearing in mind that whoever you suggest, the editor may not use them. I have talked to editors who will never consider anyone recommended by authors as a matter of course, because they assume that these people will be positively biased towards the authors. This same editor said that they'd always use at least one of the opposed reviewers. This rarely fits with journal policy. 

As an editor, I will often use one of the reviewers suggested by the authors if they fit my (following) criteria. I will make sure that I balance this with another reviewer or two not suggested by the authors. To select reviewers, I will [read the submission](#editors) and look for citations of similar studies, or techniques (depending on the type of paper). From the citation, I will find the paper (preferably published in the last 3 years) and use the corresponding author's address. I will also try to visit the website of the senior (last) author to see whether they have a lab that is still active in this area, and especially I am looking for post-docs or Early Career Scientists who cover the same topic. If they are there, I will invite them. If not, I will write to the lab head in the hope that they may well recommend one of their post-docs. This process can take a long time, especially [hunting down email addresses](#website) that constantly bounce back from the journal's editorial manager software. 

I will also use people that I know in my own network, especially an extended network. People whose conference talks I've seen or other papers in my area that I have read or cited myself. I try not to bombard my own close network too much with demands for reviews. I try not to use reviewers auto-suggested by editorial management software. In my experience, these are not suitable people. Whether this is the same for other editors, I cannot say.

If the manuscript is a resubmission, I will try to use the same reviewers that made previous reviews. This isn't always possible, and I know that it is a source of upset for authors when they receive new reviews on a second or even third round of review. I don't think that any editors will do this deliberately, but reviewers do have the option of indicating that they are not willing to reread a resubmission. If this is the case for most or all of the reviewers, then you are likely to face an entirely fresh round of peer review. 
