## Construct a logical argument in your writing {#argument}

Writing is not straightforward. Your objective is to communicate with a reader, someone who you’ve likely never met and will never meet. You need to communicate highly complex information. But more than that you need them to see things as you do. You need to provide them with your reasoning and your argument, and have it make sense to them; preferably to the point where they agree with you. 

To communicate, you need to start from common ground. The beginning of your introduction starts with the most general concepts in the context in which you are writing. The context depends on your audience, and this in turn relates to the particular journal that you are writing for. Even if you are writing a thesis, you should pick out a target journal for each of the chapters. Once you’ve established the common ground, you need to carry the reader towards the hypothesis or question that you propose. The easiest way to do this is to make use of a logical argument: 

A series of statements that introduce a starting premise, provide evidence for and against that premise (perhaps adding in an example that makes your point), point out what missing information would allow reaching a better understanding of said premise, and logically conclude that what you are doing is going to fill this gap. 

This logical argument style is most prominent in the early introduction of your manuscript, although the entire introduction could be seen as one long logical argument, with a few smaller more precise arguments being thrown in along the way. You might also use a logical argument in your discussion to explain how you deduce certain inferences from your results, or provide a logical extension for a future study. 

The following science argumentation model (Table \@ref(tab:argument)) is modified from Cope et al [-@cope2013science]. Try using this model to guide your writing of a paragraph of your introduction (or discussion) where you attempt a logical argument.

Table: (\#tab:argument) **A framework for a scientific argument.** Modified from Cope et al (2013), this model argument can be followed to provide as a way of getting started.

| *Structure*  | *Explanation*  |
| ------------ | -------------- |
| A position statement / question / hypothesis / theory / problematic | This could be the big idea in your manuscript, or one of several competing concepts that you are introducing. The context in which you are writing might mean that this idea theory needs no introduction (e.g. the theory of evolution in the journal Evolution), but you need to be confident that your audience will understand what you are proposing. Remember to cite the person who came up with the idea. |
| Claim 1 | One potential explanation or interpretation of the original idea. Evidence: Literature that agrees with this interpretation (could include an example) Reasoning: Your justification that links the evidence to the claim or interpretation |
| Claim 2 | Another potential explanation, of the previous interpretation of the original idea | *Evidence*: Literature that agrees with this interpretation (could include an example) *Reasoning*: Your justification that links the evidence to the claim or interpretation |
| Counter - claims | Other possible interpretations or counter claims. |
| Conclusions | Evaluation: your judgement on weighing up the evidence for the idea. |

If your logical argument doesn’t arrive immediately, don’t force it. Give it some thinking time to let it settle in. I find that logical arguments develop best when I’m not sitting at my desk writing. They come when I’m reading other papers (especially those with well written arguments), taking a deep, hot bath, or when I’m out running in the mountains. If you are more social, talk through your logical argument with others, perhaps over a cup of coffee. It really helps to keep the ideas turning in your head. Don’t cut yourself off from work thoughts when you are away from work. 

There are other shorter forms that might suit you better. Consider another classic form of the scientific argument: “compare and contrast” which allows you as a writer to quickly familiarise your reader with some key examples. Another sentence structure to consider is explaining cause and effect. For practical wording examplesof both of these classic arguments, [see part 2](phrasebank.html).

### Arguments in Latin
From time to time you may come across comments about arguments that you’ve made in your work made in Latin. Why do people use Latin and not simply say it in English? What do these phrases actually mean? While you may think that these people are being pompous or trying to demonstrate some scholarly superiority by quoting Latin at you (and you might be right), there is some important reasoning to consider both in the meanings of these argumentum (as they are known in Latin), and the fact that they are as old as Roman scholars, and often much older. This then is the point, that some arguments are faulty, and that this has been known for thousands of years. 

Here I have provided some of these arguments, and the reasons why they may appear in your thesis in writing biological sciences. 

_Ad hominem_ - “To the man” means that the argument attacks the person and not the argument.

_Non sequitur_ - “It does not follow”: suggests that one statement in your argument is not linked to the next. This is also known as a logical fallacy, a formal fallacy or a deductive fallacy (for a full list of fallacy statements and their explanations, see here). 

_Post hoc, ergo propter hoc_ - “it happened after, so it was caused by”: mistaking cause and effect simply because one thing happened after another. The two events may have been completely unrelated.

_Reductio ad absurdum_ - “reduction to absurdity”: attempts to establish a claim by comparing it to an absurd opposite. 

_Novacula Occami_ - "Occam’s razor": The idea that the simplest hypothesis, or argument is most likely to be correct. Another way to think of this is if you have two models that you test are equally likely (e.g. within 2 dAICs), the one with the least number of variables should be considered superior. This is also known as the priciple or law of parsimony: _lex parsimoniae_.


Likewise, there are some arguments in English that you will hear time and again. I take the opportunity to also list these here:

**Correlation does not equal causation** - That two events or variables are related when in fact they are co-incidental. 

**Absence of evidence is not evidence of absence** - The idea that positive evidence of the existence of a relationship is superior to a lack of the same evidence. This is also known as a Type II error (false negative), where the lack of finding a significant relationship does not lead to a conclusion that the relationship does not exist. Later we discuss how a [lack of finding of a significant result](transparency.html) leads to confirmation bias in science.

**Observational selection** -"The root of all superstition is that men observe when a thing hits, but not when it misses." Francis Bacon [-@bacon1620novum]. This refers to the cherry picking of studies that support your hypothesis while omitting those that do not support it. Later we see how this can be abused when writing a review or even the introduction to your chapter.

**Straw man** - Erecting a false or simplified statement in order to make it easier to attack.

**False dichotomy** - Considering that two extremes of a continuum are the only possible alternatives.

We have seen elsewhere how science is built on the works of those that have worked before us. When we construct a logical argument in science, we do so using this scholarly accumulation of knowledge as presented in the literature: citations. That is to say that your claims must be backed up by the literature. To do this, you will need to read that literature and make sure that it can back up your claims. Beware of making a baseless claim.

It may be that when researching your question, you come across the same argument using the same literature rehashed time and again in different papers (it happens). Does this give you a green light to do it again? I’d like to think that you already know that there are likely lots of other untapped and better examples out there, and it’d be well worth your while constructing your argument yourself. 

Beware of copying an argument wholesale. You might well end up getting muddled, or worse perpetuating an error. Better go back and make sure that you understand the original premise and the works that promote or oppose this. Having told you to beware, I’m now going to encourage you to read, because [reading is one of the best ways in which you can learn about writing a logical argument](criticalreading.html). 

Reading critically will make you aware of when you come across an argument. Ask yourself:

* Did you understand it?
* Was it written in a conventional style (as in the table (\#tab:argument))
   + If not, how was the style broken with and did this improve or detract from the understanding? 

In this writing book, I concentrate on providing formulaic approaches to writing, because these are by far the easiest ways for inexperienced writers. However, I encourage you to learn and experiment with writing styles as you become more experienced. [Critical reading](criticalreading.html) is one of the best ways to learn about alternative writing styles (see here): reading is probably the best way of improving your writing. Alternatively, and especially if the above hasn’t clicked with you, you can read more about writing a scientific argument (see for example [here](https://msu.edu/course/iah/231b/gifford/sciaargs.htm)). And there’s plenty more out there. 
