# Receiving the editor's decision {#decision}

[Peer review](#peerreview) is the basis of guarding and maintaining quality in science. If you’ve just got a decision from a journal, you’ll need to respond to the comments. This to and fro between authors and reviewers usually doesn’t exceed two rounds. As you approach the comments, there are several points that it’s worth bearing in mind:

- The task of the reviewer is to help improve your manuscript for the scientific record and for the reader
- The reviewers and editors have given their time freely to help you and your work
- It's easy to misinterpret what reviewers and editors say, and you need to take the time and space to respond appropriately

If you already know what it’s like to receive reviewer comments, but struggle to understand why reviewers say what they do, then it’s time for you to start [reviewing papers](#howpeerreview). You can ask your mentor to mention you as a potential reviewer (especially if they are going to decline because they are too busy). But probably the best way to get started is to participate with your lab or journal club in the review of a preprint ([see part 2](#preprint)). This has the advantage that you are not the sole reviewer, but will be in a group. Your group will get credit for their review (via a [DOI](#DOI)). You will get to discuss the finer point of reviewing with your team. Especially, you will likely hear remarks that might come across as insulting or unprofessional and it’ll give you a chance to challenge these at source, and so positively influence others.


## What to expect in your decision letter
When you finally receive it, the email will contain some stock text about the overall decision, some information about how to resubmit your revised version (if you have this as an option), and a time-frame. After the editor has signed off, you will find comments first from the Associate Editor (AE) who handled the review, and then from (typically) two reviewers, but sometimes three (or even more). It would be a good idea to add the deadline to your calender, especially if you feel that you won't be able to respond immediately. You can always ask for an extention if you are likely to go over the allotted time.


### The desk rejection {#desk}
A desk rejection is when your manuscript is assessed by a subject editor (it could be the editor-in-chief, an associate editor or any rank in between), and they decide (based on your title, abstract, cover letter, or a quick look at the content), that the manuscript is: not in the right subject area, insufficiently novel (too many similar papers), or unlikely to make it through peer review (not scientifically robust). The editor in question should explain how your manuscript failed to meet the specified editorial requirements for undergoing peer review in their journal [@teixeiradasilva2018establishing]. In my experience, this is rarely the case. Instead, it appears as if these editors are making a quick [confirmation bias](#transparency) decision based on whether or not they consider the submission will receive sufficient interest in order to match their [Impact Factor](#impactfactor) (or even inflate it). Moreover, it has been suggested that these decisions by editors are on the whole poor, with 66% of submissions being accepted in an equivalent journal without changes [@farji-brener2014rejecting]. The editors responded that their desk rejections are far more nuanced, and that equivalent journals don't necessarily have the same scope [@schimel2014editors]. You should have already [checked the scope of the journal](#whichjournal) prior to submission. The reality is that many journals have far too many submissions than they can handle, and so there is a need for an initial triage. In general, desk rejections work well for all concerned when authors know why they have received this decision. For this, there need to be specific guidelines that are followed consistently by the whole editorial team [@teixeiradasilva2018establishing]. 

On the positive side, a desk rejection is fast (otherwise, it's unfair) and there should be plenty more journals on your list. It is possible to appeal, but you will already have had an editorial decision against your manuscript, hence you will be fighting an uphill battle from the start. In terms of your time and effort, you'd probably be better off accepting this rejection and moving on. 

### Take a rejection seriously {#rejection}

Rejections are harsh, but totally normal [@cassey2004publication; @day2011silent]. Everyone gets rejections, including the top scientists in their fields [@cassey2003publication]. As a result, you will feel disheartened, frustrated and even angry [@pannell2002prose], and this is normal too. Don’t take it personally, and you'll find that the more you share the times you fail, the more you'll find that others share the experience [@crew2019here]. You will need to pick yourself up, and take your manuscript back and try again. The results of a survey among top ecologists suggests that scientists need to develop a thick skin when it comes to rejection [@cassey2003publication]. Learn as many lessons as you can from your rejection and quickly move on. Certainly, never dwell on a rejection and feel that this is anything more than a minor setback. Receiving a rejection is not an indication of professional inadequacy, also known as [imposter syndrome](#mentalhealth) [@woolston2016faking]. All of us have been rejected, and continue to deal with rejections throughout our careers. 

The most important point to discern as quickly as possible is whether or not your manuscript is not fundamentally flawed. If you receive a rejection because your study is flawed then take the time to learn the lesson. This will be a hard lesson to accept because it speaks about your experimental design, and whether or not you can really answer the questions that you set out to when forming your hypothesis. 

Do not start Hypothesising After Results are Known (HARKing). If you have made mistakes in your experimental design, then your data might be useful for a post-hoc manuscript. There is no shame in producing a descriptive note of this kind. Many researchers appear to automatically send a flawed manuscript to another journal to see how it will do there. These manuscripts are very plentiful and take up the time of a great many people (in specialist areas you see them doing the rounds of different journals). I would urge you to learn from mistakes, and not to burden others with them. Many editors try to give good advice when making rejections, and you should take the time needed to absorb this. If you believe their assessment to be wrong, and it may be, then seek out some honest sounding boards for your manuscript, such as a mentor or another colleague or post-doc. 

Sometimes, you will receive a Reject decision, and the editors comments will allude to the work not being sufficiently novel, or not sufficiently advancing the field. In other words, whatever it was that they were looking for, your manuscript didn't have it. Tacked onto the end of their email may be the offer to submit to another journal in the same stable, the so-called 'portable peer review'. Typically, these are Open Access [No Impact Factor](#noif) journals where you have to pay an, often hefty, article processing charge to get published. This is rarely a good idea. The standings of these journals is (typically) not great, and you’d probably be better off going back to your [original submission list](#whichjournal) and selecting the next journal there. Having said this, if the journal offers to move your submission with or without the peer reviews, at least you know that your manuscript is not fundamentally flawed. This kind of rejection is simply an example of [publication bias](#badscience), and it is time for you to move on from this journal to another on your [submission list](#whichjournal).


### Time taken to receive your decision {#timetaken}
Usually, you will receive a decision letter (email) after ~60 days. This depends on the journal, editors and reviewers, but it’s worth signing into the editorial management system and looking at the status of your manuscript. If after 60 days the status hasn't changed and you’ve heard nothing, then contact the editorial team (with the email address given in the editorial management system. Time to first decision in the Life Sciences was found to average 11 weeks and 25% of decisions are received within a month [@huisman2017duration]. That might sound oh so slow, but this is relatively quick when compared to the 18 week average first response in economics. 

It is worth bearing in mind that authors generally feel more unhappy with the reviewer comments they receive the longer they have to wait [@jiang2021understanding], while fast turn around times produce more content authors even in the face of rejections [@huisman2017duration]. Clearly, the difference is in the resentment of time wasted, especially for a desk rejection, or even for poor or feeble reviewer input with a rejection. If you feel particularly unhappy about long waiting times, then you could consider releasing your manuscript as a [preprint](#preprints2). Otherwise, there's little that you can do, and it can simply be bad luck when you have to wait a long time for a review. Different journals have different mean times to first decision, and some (often those with faster times) advertise this and so this may influence your decision about [where to take your manuscript next](#whichjournal).

In my experience, every manuscript is different and it's very hard as an editor to determine how long it will take to find reviewers, or how long those reviewers will take to produce their reviews. Just because reviewers accept to undertake reviews, does not mean that they will do them timeously, or even at all. After a failure to review on time, a good editor will follow up to seek out other potential reviewers. But there are other reasons why decisions may take time. 

In the case that the editor found no reviewers after looking for some weeks, one option is for them to make a '[desk reject](#desk)' and encourage resubmission. In the rejection, they may point out a number of potentially minor faults. For the editor, it takes the heat off of their desk. They may not be allocated the new manuscript after resubmission. For the authors, it's just frustrating. If you suspect this has happened then consider another journal (with a clear editorial stance on peer review), or provide more [potential reviewers](#suggestreviewers).

It is worth remembering that certain times of the year are likely to take longer than others for peer review. Editors find it more difficult to find reviewers in the summer months when many biologists are in the field or on holiday (remember that summer occurs at different times in northern and southern hemispheres). The start of the academic year is also a particularly busy time for most academics (editors and reviewers), and you might expect waiting longer (although academic years start at different times in different countries). In general, academics are busy and finding reviewers is difficult [@perry2012peer].

The delay from the end of data collection to being published can take between 0.5 and 3.5 years, depending on the subdiscipline of biological sciences that you are working in [@christie2021reducing]. This includes the initial write-up and submission time, together with any initial rejections from other journals and multiple rounds of reviews. This adds to many other arguments for using [preprint servers](#preprints) to make your work publicly available as soon as it is completed [@christie2021reducing]. 


## What to do when you receive your reviewer comments
Your reviewer comments will arrive in an email when you are busy doing something else. If you have time to read them the same day, then my suggestion is that you read without trying anything further. Remember to forward them to your co-authors as soon as possible. Simply read the comments and then close the email and mark it for further attention the next day. Your writing is very personal to you, and you might be surprised at just how hurtful it can feel to have someone critique your writing (and your experiment) without holding back. If you’ve not experienced this before, then prepare yourself. No matter how much effort you put into your text, sending it out for peer review is a really high bar. Make an appointment with your co-authors so that you can discuss the comments together. Whether good, bad, or bizarre, it is best to set aside some time to read through the comments carefully, so that you can respond. 


## Responding to reviewers’ comments with a rebuttal {#rebuttal}
The reviewers are usually given two boxes to write comments in. One pertains to the comments that you receive in your letter, and the second are confidential comments to the Associate Editor (AE). Remember that the AE is acting on both of these sets of comments, and so the decision may reflect something that is said in confidence. This is not really in the spirit of [transparency](#transparent) for peer review. The best peer review systems are open and online. 

Once you’ve found the time in your week, sooner is better than later, sit and read the comments again. Normally, they will sound much better, and less harsh, on the second read (if not, try third or fourth). They should seem far more approachable than when you first read them. Most reviews will have a set of major (when applicable) and minor comments that you need to address from each of them. Try sketching a few responses down to the major revision comments before your meeting with your co-authors. The easiest way to do this is to copy all of the comments from the email (together with those of the editor), and paste them all into a fresh document. Use a different colour text or a clear set of symbols (e.g. >>>>) to indicate which text is your responses and which is the reviewers' or editors'. Or number each comment and reply. If it isn’t clear enough, then the editor may well get confused about what is the comment and what is the rebuttal. One of the best ways I’ve seen of doing this was to make a table with all the comments in one column (each on a separate row), and the author responses in a new column. 

Sketch out your responses to the major comments, and use a tick if you are happy with making the suggested minor comments. If there are comments that you don’t know how to handle, simply leave them with a question mark. By making this start before you meet with your co-authors, you will have an idea of what is likely to be difficult to tackle in the revision. Even if you’ve received a rejection with reviewers’ comments, it’s well worth having this same meeting with your co-authors so that you can decide together what to do next. Skipping on comments from reviewers during a rejection appears to be very common [@crijns2021effect], but is a very uncollegial way of moving forward. I have personally reviewed manuscripts that were rejected, only to see them again as a reviewer in another journal with all of the same errors. 

Make a plan of how to handle all of the comments, or where to go, what to read or who to talk to (perhaps another co-author), to sort out those you don’t know. Decide whether you need to send out the journal decision to co-authors now, or wait until you have your rebuttal ready to circulate. For me this decision is largely based on how much time the revision is likely to take: if it’s quick, rather send the revision and rebuttal together with the decision. 

Next, when you sit down to write the rebuttal and revise the document, you need to make sure that you have pressed “track changes” on the submitted version of the manuscript. I find it easiest to have both the rebuttal letter and the revised manuscript open side by side on the screen. As you revise the manuscript in response to the comment, make a note to mark that it’s done in the rebuttal letter. Mark any comments that you don’t do. Your revision is written as a rebuttal to the editor. While you don’t write your comments back to the reviewer, it is worth bearing in mind that the reviewer is likely to read them. 

Three watchwords should be your guides for your response to the reviewers:

**professional     -----    polite     -----        precise**

In addition to these, make the entire process easier for everyone by:

- Making a note of the line number where the revision is made (note that these can shift around in the revision)
- If you have reworded the text, do copy and paste that rewording into the rebuttal using quotes and corresponding line numbers
- Simply use a word like “done” to indicate changes on Minor comments
- Do be polite with your responses, but you don’t get any extra points for wordy thankfulness or praise. So keep it succinct and to the point
- Signal that you agree with the comment and that you have made a change to the text

Reviewers sometimes use a chatty style, and it may appear to you that they are asking you a question. For example, they might ask you exactly how accurate a piece of equipment you used to measure your organism. Intuitively, it seems like the right thing to do is to simply answer them in the rebuttal. But they expect you to make a change to the ms, and not simply to give them an answer in the rebuttal. Otherwise, it would have been pointless in making the comment. 

Do bear in mind that your reviewer is a human, and was likely operating under less than ideal conditions when reading your manuscript. They could have been getting constant interruptions. They could have been reading it after having read another three manuscripts. They could suffer from insomnia and read it in the middle of the night with no sleep for a week. Give the reviewer the benefit of the doubt. Do remember to thank your reviewers and editors in your [acknowledgements](#acknowledgements). They’ve been working and doing the best for your manuscript without any thanks other than what you will give them. So give them a boost and help make their day that much brighter. 

### What if you don’t agree with a reviewer?
Most of the time, reviewer comments are sensible, helpful and genuine attempts at improving the quality of your contribution. If you don’t agree with particular points, try skipping them and moving ahead with the easy points or those that you do agree with. Discuss any points that you don’t agree with your co-authors. Try to get another perspective on the comment. Do your best to try to see the comment from the reviewers standpoint. 

For example, a reviewer might ask for details on a point in the methods, but they are mentioned in another section of the methods. This is a cue for you to add a flag to that point in the manuscript. For example, write: “see section 2.2.3 for an explanation of how this was done”. 

If a reviewer has made a comment that says that they don’t understand something, this means that you need to make a change in your text so that the text is easier to understand. If they don’t understand, then it could be that more people don’t understand and you want your text to be understood by all people that are reading it, so make a change. 

If you and your co-authors don’t agree with the reviewer, then make it clear what exactly you don’t agree with. Again, try to see it from the reviewer’s perspective and write a courteous and clear explanation of why they might have misunderstood or misinterpreted what was written. Back up your comments with citations, even if these aren’t cited in the paper. Provide full references for any citations you give. The more thorough your explanation of both sides of the disagreement, the more likely the editor will side with your perspective on the point that you don’t agree with. You may find that you want to include some of this text in the ms, or that you offer to provide it in the [Supplementary Information](#suppinfo) (if there’s a word limit on the ms). 

Remember that the reviewer is likely to read exactly what you write in your rebuttal. Your job is to professionally explain why you don’t agree. Forget any of the emotions that you might believe to be there. Revert back to professionalism, because you are a professional.

### When reviewers ask for additional analyses or experiments
It is not unusual for reviewers to suggest additional or different analyses, or even experiments. It will be important for you, as author, to differentiate between requests that are reasonable and stay within the original bounds of your stated hypothesis, and those that do not. Because there are so many ways in which to analyse data, it is not unusual for a reviewer to suggest you use their preferred method over the one that you submitted. Such suggestions are made with good intentions, and unless there are clear reasons for not undertaking these analyses (such as you have already [preregistered your study](http://howtowriteaphd.com/transparency.html#preregistration) or they are inappropriate), you should attempt the analyses and then make a call on whether or not they improve your work. Even if you decide not to include the results, you can present them to the reviewer/editor in your rebuttal, together with your reasoning for not including them. 

It is important to be aware of [p-hacking](http://howtowriteaphd.com/transparency.html) even in your rebuttal. Improving your work through peer review should not result in changing the focus of your work, or even including a co-variate that you did not plan to use. Many authors feel pushed into conducting extra analyses for fear of having their manuscript rejected [@hopewell2018influence]. Although it's impossible to determine every potential scenario here, if your work was well prepared and conceived, you should not need to conduct extra experiments and there should be journal policy to prevent this. 

Exceptions might include when journals ask for independent experimentation to determine a mechanism detected (or speculated on) in the manuscript. Including multiple lines of evidence is likely to have your article accepted with higher impact. You may or may not have the option of doing this kind of extra work, and may therefore need to settle for another journal. In all cases, discussions with your co-authors should help you decide on the best course of action.

### When reviewers don’t agree {#conflict}
Normally, you will have two reviews (possibly three depending on the journal policy) and comments from the Associate Editor (AE). The AE acts as a judge given the opinions of the reviewers, and so if the reviewers disagree, the AE should suggest the correct direction for you to take. Sometimes this means that the AE will consult a third reviewer (and occasionally even more reviewers). This is one of the many reasons why it is important for [editors to read your work](#editors). If the AE gives you no direction (as is increasingly the case) then make this decision with your co-authors and indicate to the AE the conflict between the reviewers and the reason why you’ve chosen the direction you have. 

### More than two rounds of peer review
You should not expect to have more than two rounds of peer review for most articles, but there are instances when this could happen. There are plenty of reasons why your manuscript might go into extra rounds of peer review, chief among these is the acquisition of new reviewers' after others are unavailable. However, the AE should be doing everything that they can to avoid this. In cases where it happens, you should be receiving helpful and specific comments from your AE. In the instance that you are making all possible changes to reviewer comments, but not receiving a clear and directed decision from your AE after three rounds of review, you can reasonably [appeal to the Editor-in-Chief](#unfair). 

Note that on occasion it is the authors that are refusing to implement changes in the manuscript demanded by reviewers and editors. In this case, you should expect that your manuscript will be rejected. The most common problem that I see, is that editors fail to state exactly what they want. Then the authors and reviewers end up in unnecesscary rounds of reviews. 

### What if you feel that your reviewer is being unprofessional?
Reviewers’ comments can come across as harsh, upsetting, rude and even arrogant. While it isn’t ok for reviewers to be rude, it does sometimes happen (see [Part 4](#problempeerreview)). If you really feel that a reviewer is being unprofessional, it is worth flagging this with the editor. I’ve never had to do this myself, but I am aware that there is some unprofessional behaviour out there (I’ve seen it on [ShitMyReviewersSay](https://shitmyreviewerssay.tumblr.com/)). Discuss it with your co-authors, but here are two potential options:

- If it’s just one or two comments, then simply indicate to the editor that you don’t feel that you don’t know how to respond. Ask the reviewer to try again, or ask the editor to interpret the comment for you.
- If it is every comment from one reviewer, write an email to the handling editor and ask for their guidance. You should find their email address in the journal submission site. They will flag it with the editor and come back with a solution for you. 

### Appealing against a decision that you think is unfair {#unfair}
From time to time, a decision comes from an editor that is clearly unfair. I’ve had a few. As I’ve mentioned before, scientists are humans and humans do have [biases](#problempeerreview) that manifest into their professional lives. This is the reason for [double-blind review](#double). Scientists in STEM are predominantly white and male, and express the views of this minority but powerful group. Their prejudices do manifest in their decisions, and it is important to push back against this when you feel that this is the reason for a decision.

Most (good) journals will have an appeals process and you should look this up and see what’s involved. While doing this, it is worth reviewing the journal’s policy on how they handle manuscripts; again, good journals should have a clear policy. Of all the rejections and poor decisions I’ve had on my manuscripts over the years, I’ve only felt that decisions were unfair and worth appealing two or three times. 

Normally, an appeal is made to the editor in chief. Be very clear about why you are appealing and what in the decision does not tally with the journal’s own policy. Remain professional and detached from the decision itself, and instead appeal on how the journal’s own policy was not followed. For example, a journal may have a policy that the editor will sum up all of the reviewers’ comments and use this as the basis for their decision. If the editor seems to have sided with one reviewer while not considering others, this can be the basis of an appeal.

Any appeal should be agreed with your co-authors before sending it. 
