# Why should an editor read your submission? {#editors}

There is a worrying increase in poor editorial decision making, because editors are not reading submissions. In their survey of Associate Editors, Poulson-Ellestad et al. [-@poulson-ellestad2020illuminating] found that they advised Early Career Researchers not to take on the position of Associate Editor unless they know that they have enough time in  their jobs. This is an assessment with which I agree. You must be prepared to carve out dedicated time in which you can concentrated several times a week, or nearly every day for the Editor-in-Chief.

When a manuscript is submitted to a journal, the submission goes to either the editor-in-chief or a handling editor based on the key words or journal section implied during submission (see [Part II](#submit)). In some journals (like [PeerJ](www.peerj.com)) the submissions are offered up to a whole group of editors who can take their pick. It seems that the next thing that happens is that the manuscript is sent out for peer review. But stop. That’s not correct and it’s really not a good way to proceed. Before sending it out, the designated handling editor needs to read the submission.

## Why is reading so important?
The title and abstract really don’t allow a handling editor to decide whether or not a manuscript should go out to review. There are a lot of manuscripts out there that should not have been submitted, because their authors do not have sufficient judgement of their own or because they believe that there is a reason to just ‘chance it’ (especially if the manuscript has been [rejected](#reject) by somewhere else already). It is very important that handling editors read the submission, because without that they are moving editorial responsibility from themselves to the peer reviewers.

Some years ago, I co-authored a series of articles [@perry2012peer] that were published across many journals about how peer review was becoming very difficult for editors because so few colleagues accept to do reviews. This was a problem then, and it’s a problem that has grown in time. I’ve recently sent out manuscripts to more than 15 people before getting two reviewers accept the invitation. That peers are not prepared to review, or in many cases even to respond to the request, is very poor. However, more recently I’m experiencing a sharp increase in manuscripts to review that should never have been sent out.

My time is precious, and it’s becoming quite expensive for my employers. I am happy to conduct peer review because it is an important part of the scientific publishing process, and I expect others to review my own work. However, I expect that any manuscript that I receive is worthy of my attention and time. If the handling editor has not read it, they cannot decide this and I really wonder what makes them think that they can send it to me (and presumably others) to read while they don’t feel that they have time to do it themselves. Moreover, this appears to be a trend among younger, less experienced, editors (often Associate Editors) that have either not received any guidance in what their job as editor is, or how to do it.

## If you are going to be an editor, then you must be prepared to read
I must admit that I’ve done it. I’ve sent out manuscripts to be reviewed even when I didn’t have the time to properly read the article myself. A a superficial skim suggested that it seemed fine. Not good. It’s embarrassing to have sent out manuscripts that should be rejected without peer review. In the case I’m thinking of, once I’d found time to read through the manuscript later on that day, I realised how bad it was and immediately wrote to those I’d asked to do the reviews and asked them not to. The article was rejected. It is important that this burden is taken on by the editor than burden two or three times as many other reviewers to make the same call.

Sometimes, it’s not clear whether or not a manuscript will pass muster. Articles can stand or fall on good or bad single judgements of the authors. But misjudgements aren’t always obvious to editors. That’s why peer review is important, and that’s why it’s hugely important for editors to send manuscripts to appropriate reviewers that have some expertise in a subject. 

Science is built on the work that others have done before, but basing your work on what someone else has written will mean that you have a good understanding of what they have done and how they have done it. Assumptions have to be made to get anything done, and it’s a good exercise to sit down with a published paper (or even a manuscript of a colleague or your own) and read through listing all the assumptions that are made. Physicists might have a very long list if they read a biologist's manuscript, but with some practice you learn to see the assumptions that the authors have made when designing their experiment, or going out to the field to conduct their study. An incorrect assumption could lead to the entire manuscript losing its value.

In my example above, the authors might assume that they had correctly identified the species when recording its call. Such assumptions should be backed up with museum and/or tissue bank accessions. But when they are not, the assumption that the authors are recording what they think they are, is vital. If this is placed in doubt, then the entire premise (description of a call to distinguish this species in the field) simply falls apart. In a case without vouchers, the assumption needs backing up by someone who knows the identification from another study, or without any foundation it becomes worthless.

## I’ve been on the other end too
I’ve submitted manuscripts to journals where the editor clearly never read the manuscript. Editors who have made a decision without any guidance of their own gives this away. If your decision comes as a single sentence that asks you to revise according to the reviewers’ comments, then you can be reasonably sure that your editor hasn’t read the manuscript (and possibly not even the reviews).

It’s not surprising that the editors have little to nothing to say; without reading the manuscript, the reviewer comments aren’t really very helpful. Without reading, the editor has no idea whether the reviewer is biased. As an editor, you simply have to read. And if you don’t have time to read, you shouldn’t be an editor.

## There is worse that goes on in economics {#economics}
If the above makes some editors in Biological Sciences look bad, then I apologise. Being an editor for a journal is a pretty thankless task and there is no financial gain when doing an editorial stint. However, if you're going to do it, then you must do it well. The half measures that I describe above are simply not good enough. But biological journals are a huge cut above those in economics. I've always had my doubts about economics as a subject. Rather like theology, it's based on a fanciful construct that puts its own practitioners in positions of power when we'd do just as well to flip a coin. 

In May 2018, I was pursued for some weeks by the _International Journal of Finance and Economics_ to conduct a review of an article submitted there. Even though I raised the flag that I was not an appropriate reviewer, the editorial assistant (not the editor) still wanted me to conduct the review. Apparently, 'the system recommended me' and this was enough for me to be selected. It appears that the problem of non-expert reviewers is on the increase. Consider this blog post by Ivan Oransky [-@oransky2021elsevier], one of the authors of [Retraction Watch](https://retractionwatch.com/) who was invited to review papers on COVID-19! Essentially, this is the result of editorial management systems ‘auto-suggesting’ reviewers, and editors not doing their due diligence to determine whether any of these reviewers is worthy of conducting peer review on that submission.

Clearly, selection of reviewers must be done by the handling editor, and those people must be chosen based on their expertise (not lack of it). While editorial management systems might help editors, they can't replace diligence on behalf of those who are responsible for the upholding integrity of the peer review system.

## Summing up on editorial blunders
The way to get round making the kind of editorial blunders I describe above is simply for editors to read their manuscripts. The guidance of how to read a manuscript should be explained to editors when they take up the position. There is plenty of information out there on the internet, but the journal’s editorial policy should be understood by all of the editors (and preferably open to authors and reviewers too), and that should include reading manuscripts before sending them out for peer review.
