# Retaining your own voice when writing {#voice}

Should one use first-person pronouns ('I' or 'we') when writing a scientific paper? Although there was a tradition not to use first-person pronouns when writing scientific articles, this has fallen by the wayside in recent years, because the use of I or we makes writing simpler for writers and easier to understand for readers. Use 'I' if you are the sole author (or in your thesis) and 'we' for two or more authors.

You will regularly see 'I' or 'we' being used in the last paragraph of the introduction and the first paragraph of the discussion. It’s also quite common to use this in the methods section. The reason why these sections have 'I' or 'we' is quite obvious, as it allows you to place your own voice on your actions and decisions. After all, it is your aim and hypothesis for your study, so you should own it. Using first-person pronouns also allows you to be more concise, and there are some great examples given by Kurt Vonnegut [-@vonnegut1980how] where you can see what happens when you don’t use them.

The first use of 'I' or 'we' at the end of the introduction is powerful. Up to that point, the reader has read four or five paragraphs of logical arguments outlining the background information that makes up the reasoning for your study. Using the first-person pronoun now makes the reader sit up as they have you communicating directly with them what you aimed to do. But that power is lost with repetition. So if you were to continuously use it throughout the methodology, the reader may get tired of reading a string of statements stating that you did this, then you did that, and so on. The power of using 'I' or 'we' is to use it sparingly to boost clarity.

## Does writing 'I' or 'we' help people to understand who you are?

Actually, all of your writing will do this. As long as you are using your own words (and not plagiarising), your writing is likely to be unique to you and hence recognisable as you. It never ceases to amaze me that it is possible to convey the same information in so many different ways. Your way will likely change with time and experience, but remain yours throughout your writing life. If you keep writing, people will be able to recognise your distinct style.

## The Vonnegut advice

Kurt Vonnegut [-@vonnegut1980how], infamous novelist, provided some advice for writers. First, he made an impassioned plea for technical writers (yes, you) to use your own writing style. The easiest way, Vonnegut argues, is to write about a subject that you care about. He's totally correct on this, and I'm hoping that after all your research you care passionately about your subject. Next, not to ramble, but to keep your writing simple. 

What is most impressive about Vonnegut's advice is that he argues from the readers' standpoint. His parting advice:

> "Our audience requires us to be sympathetic and patient teachers, ever willing to simplify and clarify - whereas we would rather soar high above the crowd, singing like nightingales."
> 
> --- Kurt Vonnegut [-@vonnegut1980how]

Having said that you should write about subjects that you feel passionately about, this does not mean that you should write with unsubstantiated passion. For example, it makes no sense to write: "'"The threats to this spectacular species surpass any mechanism known to humankind" ...unless you have substantive citations or results to back this up. Yes, it's passionate, but that should be balanced by the need to keep what you write factual.
