# Choosing your postgraduate courses

As a postgraduate student, your university should offer you a number of courses designed specifically for postgraduate students. In many countries, these postgraduate courses will be compulsory and admission to the graduate school (Admission to Candidacy) will only be made after you have completed sufficient courses with grades to qualify you. These are often made up in terms of credits that you gain for each course attended and/or pass. There are normally one or two years of these postgraduate courses followed by three years of working on your thesis project. 

Postgraduate courses are widely acknowledged as the reason why postgraduate students attain great advancement in their studies. As proof of this, know that countries that have historically never had such courses have now introduced them. Despite all PhD students already having a wide range of skills from their undergraduate and MSc studies, the skills attained from postgraduate courses are designed to augment their knowledge base to a higher level so that they attain systematic expertise within the discipline, and understand the dynamics of the frontier. Hence, these courses should not only provide the basic skills for you to understand the methods of scientific research, but they should enable you to fast-track to the vanguard of international academic frontiers. 

Given that this is actually a really long time, it's worth thinking about how you can get the most out of the courses that you choose, and how best to use this time in general. In this chapter, I will not tell you what courses to take, but try to give you some insights into how to pick the courses that you are going to get most use from, both during your PhD studies and in your life thereafter. 


## How to choose your courses

1. There will be some courses that align directly to the contents of your thesis and you should do them
1. There should be a [writing course](https://johnmeasey.github.io/Thesis-Writing-Guide/) (and if not you can follow a link to my own) that you should attend as everyone needs help with writing
1. A time management course would also be very helpful, if your university has one
1. Look back at your short and medium term goals (see [here](#Plan)) and consider which courses could be relevant in your future
1. Some courses may have certification and be essential during your studies but also useful in your following career
1. An important aim during this period is to build your network, so take note of who is teaching the courses and be cognisant how they might fit into your future network. 
1. The courses that you attend as a postgraduate may well be listed on your certification. Some courses may well endear you to certain employers, so consider your medium to long term goals (see [here](#Plan)) 
1. Do some courses just because you are interested. Given that you have already done a lot of courses at university, you are going to need some that hold genuine interest for you. Remember that diversity is an important aspect of science, so think as widely as possible

### Mandatory courses

Universities are usually very strict about their rules, but these should also available to you and so it is well worth asking for a copy. The rules for your institution may change from year to year and so it will be important to make sure that you have the relevant version, and if possible get these from the person responsible. These rules may also include other important information regarding the examination process (see [Part 1](#criteria)).

The compulsory courses mainly refer to the participation of graduate students in academic activities, teaching practice and social practice. As the name suggests, these are mandatory for all students and so there is no need to consider any choices here. It may be incumbent on you to ensure that you have fulfilled all necessary credits for these courses. For this reason, I suggest that you are familiar with the current rules of your faculty. 


### Elective courses

Although you have your mandatory courses decided for you, you also will likely have the opportunity to do some elective courses. If there are elective courses that are a close fit to your thesis topic, then clearly you should elect to take these courses. The advice here comes more for other points that you may want to consider if you have credits to make up and cannot decide what to do.

1. **Consider your timetable:** You will have a timetable that you need to work to and make sure that you can physically get to a course as well as fit it in with your other mandatory and elective choices.
1. **Where does the course happen?:** the courses may take place in another campus or online. This may suit you better, or prohibit you from attending.
1. **How many credits does the course carry?:** You will need to make up a total amount of credits to gain admission to your postgraduate school. You might need to trade-off the time required for a course and the credits that it gives.
1. **Consider something from another faculty:** If allowed in your institution, consider taking a course given in another faculty. Some might be very challenging if you have no undergraduate or MSc experience, but others could be very rewarding. 
    1. Social Sciences - very useful courses might include GIS courses in geography, 
    1. Social Sciences - many biological systems have important human components that can really only be solved using questionnaires
    1. Social Sciences - philosophy has some very important lessons for biologists, especially in relation to logic and hypothesis building
    1. Art - There is a lot to be said for having a creative elective. A surprisingly large part of the process of doing science is actually creative. If you can conduct a course that will stimulate the creative part of your learning, so much the better. 
    1. Medicine - _Homo sapiens_ has become an excellent model organism, and might be much better studied in the same areas that you are working in. 
1. **Something enjoyable** - the chances are that some of your mandatory courses are going to be less enjoyable, so it's fair to give yourself something more enjoyable to look forward to during your week. 


### Certified courses

You may find that attending and passing some postgraduate courses will provide you with a certificate. For example, you may need to attend a course on laboratory animal management and welfare. Certificates from such courses may well be advantageous to you in your career following your postgraduate studies, making such certificated courses particularly attractive.


### Attending a postgraduate course at another institution

Some universities allow their students to attend postgraduate courses at other (usually nearby and affiliated) universities. If you know of a course that it being conducted at another university, but that you would like to attend, it might be worth approaching your postgraduate teaching co-ordinator to ask them if you can go.

There may also be the opportunity to conduct a postgraduate course online. Again if you know of one, or put in the time to find an appropriate one, it may be worth approaching your postgraduate teaching co-ordinator to ask if you can do it. 
The most important consideration is whether or not your institution is able to use marks generated at another institution in their own system to assess your postgraduate courses. Even if they don't allow you, it's worth talking to them about it as it may help those that come after you to find the course that they want. Or it might help stimulate to offer something similar at your institution in future.

## Due diligence during courses

You need to make sure that you get the most out of these courses. Your attitude toward each course will be an important aspect of how well you perform and enjoy the course. Hence, if you feel that one of your mandatory courses is a waste of time and you wish you didn't have to do it, you will be unlikely to get much out of this course. On the other hand, if you have a positive attitude towards all of your courses (mandatory and elective) you will likely find them much more interesting and useful to your time as a postgraduate student.

Looking back at being an undergraduate, you may have been focussed on grades or short-cutting work on courses, but for postgraduates this must have changed. You should understand by now that learning is a two-way process and that engaging with your teachers is a vital part of improving your understanding of a topic. Your teachers are likely to have an incredible depth of information on the topic that they are teaching you, and probing this knowledge will help to to appreciate the subject and help you garner new interest. Therefore you should engage with your teachers on these courses. Remember that building your network is an important aim for you during this time.


## Building your network

Courses are designed for postgraduates and usually taught by the most experienced professors. Use your time with them to [increase your network](https://howtopublishscience.org/advisorless.html#networks). You should be using the courses to network among as many fellow postgraduate students as possible. There are likely to be people using your approaches and techniques in various other disciplines within your university, and making these connections can be very important in the future.

In addition to the professors that are giving your courses, you will also learn about other academics at different institutions. While these people may be far from you, their work can be very relevant to your own. Using your time wisely on your course also involves reading work by these people. If your advisor agrees, then it may be possible for you to approach some of these top researchers to participate on your committee. 


## Time off from courses

As you are in the biological sciences, there may be good reason why you need to go on a trip and not attend part of a course. For example, your advisor may ask you to participate in lab fieldwork that is relevant to your project. You may want to attend a conference to present the results of your MSc work. You may have any number of private or professional reasons why you need to miss lectures or parts of your course.

 - Inform the course co-ordinator. Your institution may have a system where you require to be signed out of the class. Make sure that the course co-ordinator knows, and the lecturer of the missed classes (if this is a different person).
 - Catch up. Be diligent and catch up with all of the missed course work. 
 - Try to miss as little as possible. Taking your courses seriously means missing as little as possible. 

## Make the most out of learning

I you haven't already worked this out for yourself, learning is a real gift and the postgraduate courses you are offered at universities are probably the ultimate in their level of sophistication and knowledge transfer. Remember that your attitude is key in this process, so be sure that you are mentally prepared to having a positive attitude to all of your courses. Take this opportunity seriously and you should find it extremely rewarding. 
