# Academic phrasebank {#phrasebank}

It can be really tough to get started writing especially if you are writing in English as a foreign language. It could be that the academic phrasebank is just what you're looking for. 

When reading papers, I often come across the same phrases time and again. They seem so well honed to the situation that I’m envious about how the writer dreamt them up. Using them isn’t quite [plagiarism](#plagiarism), but then they don’t regularly fit the exact situation that I’m looking for. 

Imagine cutting and pasting these phrases into a file, or even better a database that’s ready for any eventuality. Banking them over time so that they are always available.

Then imagine that you did this and made it available to everyone…
http://www.phrasebank.manchester.ac.uk/

Well, John Morley has already done it, and he’s made it available to everyone. The academic phrasebank is a fantastic resource:

[**the academic phrasebank**](http://www.phrasebank.manchester.ac.uk/)

## How to find the phrase that you need:

- Look across the top for different sections of text that you are currently writing.
- Then look down the left-hand side to see the type of language function that you need. Click on something that looks applicable and watch the database open up.

## Getting started 

It strikes me that this is going to be a fantastic resource for those of you who are not writing in English as your home language. And for those of you who just need a few words to get started. It’ll also be useful when you are wanting to wordsmith your introduction or abstract. 

Is it plagiarism? The preceding chapter is all about not copying and pasting, am I now telling you that it’s ok to copy and paste? Most of these phrases are less than five words or you will find that they are non-consecutive parts of a sentence. I don't think that most of these would constitute plagiarism if you pasted them into your document. However, I would suggest that you spend some time refining what you've written and that when you do that, some of these phrases may then come out.
