# What is needed for your research proposal? {#proposal}

In my institution, you need to have your PhD or MSc approved by a group of 3 independent staff members (i.e. not including advisors) in your department. The department requires that your written proposal is publicly available to everyone in the department to look at prior to the oral presentation of your proposal. This is not unique to my university, many institutions require that you formally propose the work that you plan to do in a PhD. They may all have very different requirements. It is well worth checking out what your institution requires and by when. Talk to your advisor about this. 

Your proposal is a collection of documents, where each document is a chapter of the thesis. Ideally, these should be bounded by an introduction, which gives the bigger picture of how the thesis is placed, and a time-line at the end that demonstrates how you can complete the thesis within the two or three years for your MSc or PhD, respectively.


## Structure

Your final thesis will be a set of papers (data chapters sandwiched between an [introduction and discussion](PhDintro.html)), and so prepare the proposal in the same way. That is, you will normally have two (MSc) or five (PhD) data chapters. In the proposal, each chapter will consist of three parts.

## Proposal introduction

I’m not going to go into what’s inside the introduction here, as it’s already been done in other chapters on formulaic writing (see later in this [part](formula.html)) and specifically about the introduction (see [part 3](introduction.html)). Although you may feel that there's no point putting a lot of effort into this introduction it serves as a literature review for your upcoming PhD study, and is well worth the time and effort. 

## Methods and Materials

What’s in the [Methods and Materials](methods.html) section is also covered here. Essentially you need to:

- Introduce important aspects of your study organism and/or study site
- Describe exactly how you’ll set up your experiment and/or collect your samples
- You must explicitly state how each of the variables (introduced in the [introduction](introduction.html)) is collected
- (If necessary) Describe how you’ll turn your collected data into the variables needed for your analyses
- Data analyses (how you’ll test your [hypotheses](hypothesis.html)). This should include a description of the statistical or analytical techniques. It’s useful to structure this section by each of the questions/hypotheses that you are posing

## Hypothetical Results

It’s a very useful exercise to imagine how results will show that you have (or have not) accepted your hypothesis. You can’t show results that would cover every eventuality, but give some typical scenarios that you think may happen if you accept and reject each hypothesis. This could be a bar chart, a map, a scatter-graph, etc.

## Your proposal - what is it good for?

Once you’re done with your proposal, you might feel that you’ve done an awful lot of work without having added anything towards achieving your PhD or MSc. However, it’s actually a really useful document that you can use in a number of ways:

### Copy and paste directly into your thesis

One PhD student estimated that she pasted 60-70% of her proposal text directly into her thesis. This included nearly all of the methods and materials section verbatim. Note that this **is not** plagiarism, but [developmental recycling](#develop). 

### Use it to raise money to do your studies. 

Writing grant proposals is essentially the same as your thesis proposal, and so you can use this document (with some modifications to tailor it to the grant objectives) to [raise money](funding.html) for your work. 

### Deposit the proposal to conform to Design and Analysis Transparency

This is the subject of another chapter (see [part 3](transparency.html)).
