# Generating funding for your PhD research {#funding}

To be honest, writing a funding proposal is an art in itself and should be the subject of an entirely different book. What is written here is only really scratching the surface, so I suggest that if generating funding for your PhD research is going to be a large part of your work then you should look for an additional book. 

## Funding databases 

Funding is one of the most important aspects of doing science, and something that different emphasis is placed on in different parts of the world. In North America, in particular, some graduate students are expected to be able to demonstrate that they are able to raise their own funds, as this is expected of them in their jobs as academics. No matter where you are, your CV will be greatly improved by showing prospective employees (or labs) that you can generate your own funding. North America has a lot of opportunities to apply for funding for all sorts of reasons. There are less opportunities elsewhere, but the pool of people applying is also smaller. There are now so many opportunities, that several databases exist to help you find appropriate funding for your particular situation.

I am only going to address some of these portals, and to quickly consider some of the major reasons why you might want to apply for funding.

## Reasons you might want to apply for funding:

- To improve your CV. Even if it’s only a small amount of funding that you apply for, it will make your CV look better. You might also want to search for prizes. Academic prizes carry both money and that feel good, look good feeling that CVs need.
- Your project is unfunded. If you are completely unfunded, or you have a bursary but no running expenses, then you are going to need money to do your work. The more work (particularly field work) that you want to do, the more money you’ll need to raise.
- Your project is funded, but you want to do more. If you want to do a lot extra (like side projects or paying assistants to collect extra data) then all of this is possible if you can raise some more money to do it. 
- You want to attend a conference or workshop. There are great opportunities for travelling around the world, but they cost money and international conferences are often very expensive.
- Publishing in Open Access journals. I find the idea of putting cash into the pockets of publishers abhorrent, but you may have little choice. There are some opportunities to get funding for OA publishing. 
- It is clear that without making an application, you won’t get any funding. But where do you start?
Databases. There are many databases, but here are 3 that are easy to use. 

### Mendeley:https://www.mendeley.com/ 
This is probably my favorite. It’s easy to use and apply or remove filters. You can use the same login that you have for the referencing software and SCOPUS. 

### Open 4 Research: https://www.open4research.eu 
For this you’ll need an academic email address to register, but you’ll get access to their research database. It is nice and logical to use, and you’ll find local and international funding opportunities. 

### Research Professional:https://www.researchprofessional.com/ 
You’ll need to create a login for this site, although you might get an in with your university address. This provides you access to what could well be the same database as those above. This is a slick database and relatively easy to use.

### Opportunities in your department or societies:
Probably the most likely place to get funding is where you already have an 'in' (where you are already known). This will include professional societies where you are a member, or your department or university. These places also have prizes, so it’s good that you know what is on offer in order to benefit the most. 


