## When is it good enough to submit to my advisor? {#goodenough}

Once you've read and revised the draft text three times yourself, and you feel that you can't really improve it any more, hand it over. Personally, I need to wait a day or more between drafts when I work on something else, or do some reading. I find that it really helps to think about writing while not writing. Run through the arguments in your head when you are doing something else. That could be time in the gym, out running, cycling or swimming. Or talk through the logic of your argument with a friend or colleague while having coffee. You’ll find that spending time thinking away from sitting in front of your word-processor will be really valuable in promoting productivity once you sit down again. 

If possible, hand it to an office mate or other friend first. Your reader shouldn't have to be an expert in your field, but only needs to have a loose grasp on scientific writing to follow any paper. As a guide, any recent graduate of a biological sciences degree (BSc) should be able to understand. This makes it easy to find lots of potential readers for your manuscript before handing it in.

__In summary__

Writing a paper as a formula is not the only way of writing a scientific manuscript, but it has two really important qualities which I recommend: 

1. it makes writing easier, and 
1. readers will be familiar with the style and this will help them understand your work.
