# (PART) Part 3: After your paper is accepted {-}

# Now that your manuscript has been accepted {- #part3}

This part of the book gives you information on some actions that you might want to do after your paper is accepted for publication. Much of this section is concerned with publicising the results and content beyond academia and for non-academic audiences. Even if you feel that there would be no interest beyond your academic niche, it would still be worth making some effort to publicise and popularise your study. 

## The Version of Record {#VoR}

An important concept to understand in the publication of your article is the Version of Record (VoR). This is the final typeset version of your article that is published. 

In this millennium, the VoR had changed from a hard copy that was printed and bound into an issue of a journal into a pdf that appears at a journal website online. In addition, the VoR no longer has to belong to a volume or an issue, and is usually the first version available online [@haustein2015when]. The VoR can appear online long before it appears in an issue or volume (i.e. without page numbers), but still be the VoR. 

### Registration to obtain a DOI

If the publisher is a [Crossref](https://www.crossref.org/) member (most are), they will register the content and assign it a [Digital Object Identifier (DOI)](#DOI). 


### What does having a VoR mean?

 - This means that if you wanted to make any changes to this first printed version (the VoR), you'd need to publish a separate [corrigendum](#corrigendum)
 - The date of the VoR has an impact on [primacy](#whatjournalfor)
  + in taxonomy, for example, if there are two descriptions of a species, the earliest one counts as the valid one
