# (PART) Part 3: The formula of a chapter {-}

# Writing the sections that make up your data chapter  {#part3}

Getting over the cognitive inertia of starting to write is top of the list for most of us. The approach provided here is to present you with a formula that breaks down each section into smaller more reasonably sized chunks. However, you still need to make a start. Procrastinating starting to write is normal. It seems a massive task, even if you’ve done it lots of times before. You want to write the best manuscript that you can, but you aren’t feeling on top form today, so doesn’t it seem a better idea to wait until tomorrow? It’s not. You must start today and start now. Don’t set the bar so high for your first draft. In fact, don’t set any bar other than a personal goal of getting the first draft done. 

For the first draft, type away confident in the knowledge that 90% of the first draft will get junked or changed so much that you won’t recognise it. That’s ok, and it’s not a waste of your time. In fact, the first draft is invaluable in getting your ideas and perspective down on paper, allowing you to better organise and sift through your thoughts and bring clarity to your manuscript. Allow yourself a reward for finishing your first draft, something that you won’t do until it’s done. 

You can make life easier for yourself by changing the order of what you write. Although I have placed the contents of this chapter as you’d expect to see them in a typical paper, this is not the order I would suggest that you write them in. The most important part of writing up your chapter or paper is to have your hypothesis or question clearly stated. Once you have this, it will help you to know the literature that is already there and so writing the introduction next seems logical. Of course, you may already have [your proposal](#proposal) to work with, in which case you can start by reviewing what you already have and deciding whether or not you need to tweak this, or if you need a fresh start. 

The methods and materials are the easiest section to write first, especially if you've already done the practical work. This section will also help you focus on the analysis that you are doing for the results. Again you should review your proposal and see whether there were any significant changes to your planned methodology and note them down. This will not be an issue even if you have [preregistered your proposal](#transparency), you simply need to provide a rational explanation for why things changed.

Next, write the results. Remember that you are only looking to respond to your hypotheses, preferably using your (preregistered) proposal plans. Tables and figures are compiled along with the results. Now you have the materials and methods together with the results in full. I suggest that you make a list of all the relevant discussion points you want to make and then turn your attention to the introduction. Begin with an outline, before you flesh it out. 

Lastly, write the abstract. Populate your article with references as you write. While you can leave the formatting of references until the end, it’s dangerous to not put citations in as you write as you are likely to forget which paper is which by the end.
