# Once your paper is accepted {#accepted}

The day your paper is accepted, tell your co-authors. If they are in the same physical location as you then buy a cake, and celebrate with them at tea time. If cake isn’t your thing, then find another appropriate treat for you and your co-authors. It’s a great achievement and something you should share together. If you aren’t in the same location then make a plan for next time you meet together, even if that’s only online. There is real value in celebrating the positive times in your time as an Early Career Researcher. We all know that sharing the times when you are [rejected](#reject) will improve that experience. Similarly, celebrating the good times will give you more impetus to keep pushing through the down times. Extending this positive feeling to your co-authors, or those in your laboratory will always be appreciated.

Remember to make sure that all of your co-authors have a copy of the accepted version of the manuscript. Sometimes referred to as a **postprint**, you and your co-authors should submit this to your institutional repository so that the article can be reached as [Green Open Access](#green) by anyone who is interested in reading it.

At the same time as your manuscript is accepted, or shortly thereafter, the publisher (if you are using a traditional style publisher model) will tell you when you can expect to receive the proofs. 

## Take your time with proofs {#proofs}

The next step in the publishing process, once your paper has been accepted, is that it will go for type setting. Depending on the journal and the publisher, this process can proceed in several ways. Typically you will receive a notification that your paper proofs are ready and that you need to check and return them within 48 hours. 

Some journals may have an additional __copy editing__ (also known as sub-editing) step. This is essentially an extra step checking journal style, syntax, punctuation, spelling and grammatical consistency. The copy editor may be tasked with checking additional issues, like species names (taxonomic authorities), names of chemical compounds used, etc. All will check citations against literature cited, and check that literature cited is sufficient to link with [CrossRef](#CrossRef). Most journals that I have worked with roll copy editing and proofing into a single step. 

If you haven't checked proofs before then it is important that you read the instructions from the publishers, that come with the proofs, carefully. They should tell you exactly what to do and if you are unsure about anything then talk to your co-authors.

Typically the publishers will send you a set of queries (copy edits) that relate to your proofs. They always ask you to check every author's name and affiliation. Other typical errors are that there are citations in the text that are not in the references. Or that there's literature in the references that are not cited.

The process of checking the proofs is very important. Errors can creep in during the type setting stage. Equally, copy editors can get it wrong, and you should read the text very carefully to make sure that errors have not been introduced. Pay special attention to the tables, table legends and figure legends. 

You may also have the opportunity to change the size or orientation of figures, especially if it looks like they are not well presented in the proof. If the journal prints into columns, they may choose to put your figure in one column instead of across two. Another option is to have your figure in landscape across the whole page. Journals are generally pushed for space and so may refuse some requests for more room for larger figures. But you might get lucky if you make a good case.

Although the proofs are the responsibility of the corresponding author, it's good to get as many eyes on them as possible in order to spot any possible errors. Some journals let you know when proofs are likely to arrive, in which case it's a good idea to alert your co-authors and ask them whether they are prepared to look at them within that temporal window. I usually suggest that you make all your own corrections first before sending them around. Worst is for everyone to make their own corrections independently, as you'll have to put them all onto one set of proofs, and everyone is likely to spot some of the same errors.

Many publishers want to proofs back in a hurry (typically 48 hours). If you don't have the confidence to correct proofs yourself, or cannot pass it around your co-authors within this deadline, then you can simply write back and ask for an extended deadline for your proofs. It is important to get it right, and much better than having to correct the paper later.

It is important that you make any corrections needed on the proofs. They are important to get right because once the proofs are submitted and the [Version of Record](#VoR) is produced, any changes that you may want to make will require an official correction in the form of a [separate publication](#corrigendum). 

Probably the easiest way of doing proofs is to print them out and go through them with a pencil first. This allows you to take your time and you're more likely to spot errors this way than on the screen. However, some publishers will require you to submit proofs in an online system (effectively working with their LaTeX document). You should still have an opportunity to print and take your time with the proofs though, and these systems do allow for this.

Sometimes, there are a lot of problems with proofs, and you may not have the confidence that the publishers will make all the corrections as indicated. In this case, you should ask to see another round of proofs before committing. Most publishers will happily send you a second round of proofs.

## The DOI for your paper {#DOI}
The Digital Object Identifier (DOI) is an international standard (ISO) unique character string to identify physical, digital or abstract objects. The DOI is a "persistent identifier" or "permalink" which means that it remains unchanged even if the document itself changes location. For example, if the society that owns the journal changes their publisher, the DOIs of all content remain with the same documents even when they leave the old publisher's website. This means that although the publisher will provide a link to their website, and you may have your own repository with a link to your paper, you should rather use the DOI as the link to give out to everyone.

When you cite the DOI, don't take it apart, but provide the full link. For example, https://doi.org/10.1242/jeb.233031 should never be abbreviated to 10.1242/jeb.233031 or doi.org/10.1242/jeb.233031. 

You will note that old DOIs look different (they used http instead of https protocol, and typically have dx.doi.org addresses), but you should not edit the start of their address, but leave them. For example: http://dx.doi.org/10.1098/rspb.2018.2528

Sometimes your article may acquire several DOIs, for example from the publisher and from the preprint server. Sites like figshare and ResearchGate, assign different DOIs to content uploaded to their platforms. These are DOIs but they’re assigned by DataCite, another DOI registration agency. The different registration agencies provide different services that relate to DOIs and their associated metadata (from construction to the movie industry), and have different requirements for their member organisations. To prevent ambiguity, you should always use the DOI associated with the [Version of Record](#VoR). The biggest player registering content in scholarly output is [CrossRef](https://www.crossref.org/).

There are still some journals that do not issue DOIs. But the cost associated with adding DOIs by small publishers is changing, and so it is likely that in future a DOI will be associated with all scholarly output.

DOIs are extremely useful as you can usually click on an active link DOI and go straight to the article in question. Therefore it is well worth adding the DOI to your references if you can. Most reference databases will do this automatically, but if they don't pick up the DOI for some reason, then it's worth adding it yourself. Some journals will demand it, while others have yet to come around to how useful they are.

However, DOIs cannot replace references, otherwise we’d need to be able to click on every link all the time, and couldn’t read any paper without a connection to the internet. It’s still really useful to be able to read a formatted reference at the end of a paper.

Publishers normally deposit DOIs and other metadata (authors' names and addresses, publication dates, title, licence, funders, etc.) around the time the article is published online. This is called content registration. This is not just for articles, but also preprints, conference proceedings, books, book chapters, peer reviews and more can all have their content registered with CrossRef. The standardisation of this metadata means that not only is it possible to immediately find your article (the DOI is a link), but all of the metadata associated with it can be cross-referenced. This is of great help to funders, for example, who can look up all the products that their funding has produced without having to contact all of the people that they funded. 

### DOI Tools
If you can't find the DOI for an article that you want to cite, then there is this very useful online software that will provide the DOI if there is one for every reference you enter: https://doi.crossref.org/simpleTextQuery or use the Crossref Metadata Search: https://search.crossref.org/references

There’s an equally useful database that provides BibTex for DOIs that you enter: https://doi2bib.org/

## Add your paper to your ORCID account {#ORCID}
The ORCID (https://orcid.org/) number was devised to provide a common platform for authors to curate, and now some journals and funding authorities won’t allow you to submit or apply without one. This helps when there are authors with common (or even identical) names. As an NGO dedicated to helping scientists ascribe [credit for their work](#rescognito), should be supported. ORCID will also help prevent author fraud (see [Part I](#authors)). 

If you added you ORCID number to the metadata when you uploaded your manuscript, your ORCID record should be updated automatically (through Crossref) when the DOI of your article appears online. Inside your ORCID account, you can grant permission for Crossref to update the records automatically, otherwise you will need to log onto ORCID from time to time and approve changes suggested there. Alternatively, you can add works to your ORCID record via [Crossref Metadata Search](https://search.crossref.org/references).

Be careful not to create duplicate accounts, and make your ORCID available to your collaborators so that they aren't left guessing at your identity when it comes to submitting a paper. ORCID allows you to create some useful links for [your website](#website) or a QR code for adding to posters and presentations. If you find you have a duplicated account, it is simple to remove it (see [here](https://support.orcid.org/hc/en-us/articles/360006896634)).

## Once you have a publication date
Once your paper is published you have an opportunity to publicise it yourself. There are lots of different ways to do this, [see the next chapters](#populararticle). Some funders and institutions will want to know about press worthy publications before they are published, so that they can prepare a [press release](#pressrelease).

## On the day you publish
This is a great opportunity to contact all the people who helped you in your study and send them a PDF of your paper. The easiest way to do this is to go to the acknowledgements section and write an email that includes everyone that is mentioned in the acknowledgements. Write them a nice email in which you thank them for their help and explain briefly the significance of the paper. 

It is a very good idea to keep all of these people informed about your publication as soon as it is published. You really want people in [your network](#network) to hear about it from you first and not from somebody else. This includes contacting any authorities that have issued permits. You may also want to contact funders. 
