# Writing a press release {#pressrelease}

Many of the aspects to do with writing a press release are similar to those needed when writing a [popular article](#populararticle). Try to make your text newsworthy. Remember that journalists are looking for new things that's why it's called 'The News'. Your press release must be about something that has happened recently. There's no point in writing a press release about a paper that was published six or nine months ago. It’s very unlikely that you’ll find anyone interested in writing something after that amount of time.

Here are 10 simple steps to consider when writing your press release:

1. __Choose your hook__. The paper that you wrote may have several important findings. You are going to need to choose one easy to understand finding for your media release. It's usually quite simple to decide; take the thing that would most impress your Auntie Fanny. 
1. __Write your headline__. Like choosing a good journal title or a popular story title the headline should try to encapsulate the study perhaps with a witty angle. Don't make it too long, eight to ten words at most. Most importantly your headline should connect with a wide and general readership. There's no need to get too fond of your headline because, if they take your story, news outlets are likely to want to write their own.
1. __Crafting the first paragraph__ is important. You need to sum up the study together with the finding. Even if your reader only reads the first paragraph they should have an understanding of what you've done and found. This first paragraph should not be longer than 30 words.
1. In the second paragraph, you should __state who you are and where you are from__, both geographically and the name of your institute. Here you need to concentrate on getting across the information on why you're finding is interesting. A typical second paragraph might read: 

>Dr Frankella Smith from FitsSimon’s University found a new species of woodlouse when bending down to tie her shoelaces last month. She published her findings today in the journal _Cobblers Oniscids_.

5. In the next two paragraphs you should simply explain more about the background to your story and why the finding is interesting. Don't be tempted to deviate from the hook that you've chosen. After reading these two paragraphs your reader should be able to answer the question: So what?
1. Finally sum up your finding with a quote from you, the author. Either use the quote to emphasise the study results, or you can try and humanize your findings. This means a way of connecting with the reader, especially if you feel that the rest of your texts won't:

> "I never expected to find such a pretty woodlouse in my shoe", said Frankella. "I was flabbergasted when it turned out to be new to science."

7. Include your name and contact details of the person that the press should contact in order to find out more about the story. 
1. Give the full citation to the paper with all the author names and the journal name plus a link so that any journalist can find the full text online.
1. Include one or two photographs or relevant graphics that the press can use. If they are not taken by you then make sure that you have permission to use them. If you can, include a picture of the study organism, or even better of you with the study organism. 
1. Seek feedback. Send your press release to your university’s press office and ask for feedback. Those are the professionals and they should be able to help you. 

Of course, the better your press release is, the more likely it will be that people will write about it. Remember that it also matters a lot about the subject of your paper. The media are likely to be far more interested if your work is on dolphin communication than if you are writing about isopod communication (just like your Auntie Fanny). Having said this, never be put off just because your organism or system isn't cute and cuddly. Try asking your non-academic friends about the newsworthiness of your press release and see what they say.
