# Why write a popular article? {#populararticle}

There are many reasons why it is important to communicate science beyond your own discipline and into the wider public forum. Primary among these is that in a society based on decisions made on the basis of science, it is our responsibility as scientists to make sure that we make the findings of our work, upon which basis political decisions are made, understood to the widest of audiences. I do not mean that we are sharing science pejoratively to an ignorant public, but instead as equals in our collective scientific society. We share with a wider public in the same way that we share with those who are used to reading a well reasoned newspaper article, or listening to an informed political debate. By sharing our work, we help affirm that decisions should be made objectively, and we make the most important connection by reaching out to the rest of our society and to join them in the scientific project. 

**Here are some extra reasons why communicating by writing a popular article might be right for you:**

- Inform tax-payers who funded research what you found
- Increase profile of your work and you as a researcher
- Reach other researchers (who also read popular articles)
- Reach other stakeholders like practitioners or policy makers
- Open more doors to other potentially cross-disciplinary work
- Gain new insights into how your work appears to the general public
- Public communication is a key part of social responsibility, quickly becoming a key aspect of an academic career
- Maintaining and furthering the Scientific Project

The sooner that you come to terms with the need to communicate your work more widely, the more comfortable you will be when you are contacted by a reporter, a vlogger or someone from TV or radio. 

## Here’s a quick guide on how to get started writing a popular article.

Just like any writing project, there is no one way to write a popular article. I provide the following advice in order to get you started. You are, of course, free to write however you think your work will be best understood and appreciated.

### What’s the hook?
Your popular article will not be the same as your paper. You should plan to have a single fact or message that you want the public to walk away with after reading your article. This is likely to be the same as the main result in your paper. 

When composing your article, you need to be single minded about achieving the understanding of your hook. The article cannot take any side roads or distractions, but must stick to the main point. Once that’s done, provide the “so what” that allows the reader to see the bigger picture, and maybe where you would go next.

### Don’t get complex or technical
If your whole article hinges on something technical, you might have to start by explaining it simply. If you can’t easily explain it, then this is probably the wrong subject for a popular article. Don’t worry about leaving out (what might be to you) key details, you can always refer the reader to your article if they want to know more. 

### Always refer to your published work
Make sure that you always have some reference to your work that’s published. Provide a hyperlink, but preferably give the full citation. Be aware that news items count towards the [altmetrics](#altmetrics) of your article, so be sure to link it correctly. 

### Pictures, videos and even sound files
These are great to help readers engage with your work. Try to choose images that tell the story with the same information as you have in your article. If you don't have any, then try asking your co-authors, and then try to remember for the next project that you need to collect these when doing your research as it really helps when publicising your work.
