# Is Open Access good? {#openaccess}
Open access appears to be a great initiative that acknowledges that everything should be free to view. Neither scientists nor the public that fund them should be barred from accessing the knowledge that they produce. What could be wrong with Open Access? Many people have written a great deal on what has gone wrong, and what I provide here (and elsewhere in this book) is not the last word as this is a dynamic topic that is changing all the time.

## So what is open access?
I have covered the many different kinds of Open Access (OA) elsewhere in this book ([see part II](#openaccess1)). Here I concentrate on the fiscal implication of OA. Someone needs to pay for the work done. Who should pay and how?

The principle of Open Access is something that is easy to appreciate, and lies very much at the heart at the movement from [closed to open science](#openscience). Some history is appropriate when we talk about Open Access, because the movement started as a genuine attempt to change the publishing model for the better [some key texts including those by @poynder2019open; @poynder2020information]. Hopefully in the future this experiment will be seen as a success. In the meantime, Open Access has been hijacked by publishers as a way in which they can earn large amounts of additional income. The story of _PLOS ONE_ is useful to see how this change came about.

### _PLOS ONE_ {#PLOS}
The Public Library of Science (PLOS) started soon after the turn of the new millennium, primarily as a concern to the [problems with peer review](#problempeerreview) that are highlighted elsewhere in this book. This really was a new experiment in publishing, that was to radically alter the publishing model in the 21st century, and in only ten years, _PLOS ONE_ became the world's biggest journal. The idea was to do away with all the normal waiting times in publishing, and to have articles published immediately online, and without any charges associated with accessing them: Open Access. At the time, this was all fairly radical, and it became very successful with a large amount of interest from scientists who submitted their articles to PLOS. But the founders were frustrated that they were rejecting a lot of papers that were technically good, but not selected as they were not novel, or did not significantly advance their field. In 2006, PLOS dreamt up a new journal to take all of these technically sound manuscripts, and this was the birth of _PLOS ONE_.

From the outset, _PLOS ONE_ was not interested in acquiring any [Impact Factor](#impactfactor). Instead, it was mostly interested in taking technically sound manuscripts irrespective of their results. This meant that reviewers for _PLOS ONE_ were (and still are) asked to assess the technical soundness of a manuscript, and not to judge the 'value' of the results. The original idea was that reviews should be post publication, through comments made on the website after the publications were posted. The initial review then, was simply meant as a preliminary check for technical soundness. This was again a radical departure from the publishing norm by the PLOS group, when many other journals were still [rejecting](#rejection) manuscripts that had no faults other than they were not attractive to editors. _PLOS ONE_ was opened to accept all such manuscripts, effectively doing away with [publication bias](#badscience). As you might imagine, at a time when academics were under pressure to ['publish or perish'](#publishmore) rejections were plentiful and so manuscripts quickly found their way to _PLOS ONE_. Because _PLOS ONE_ was also Open Access, it's papers received an extra boost of citations through visibility, and ironically after five years it found that it had an Impact Factor to rival some of the journals whose rejections it was picking up. This meant that more and more scientists started submitting to _PLOS ONE_ as their journal of choice, mostly because it was publishing Open Access.

_PLOS ONE_ became the worlds biggest scientific journal, and in 2013 it published 32058 papers [@davies2019plos]. It's worth taking a moment to do the arithmetic on the income that PLOS received for these at > USD 1000 per article (so it seems inconceivable that they could make a [loss](#loss)). By this time, other academic publishers had noticed the rocketing ascent of _PLOS ONE_ and had responded by starting their own 'no impact factor' journals that could be fed by the rejection piles of journals already in their stables. Notable among these was _Scientific Reports_ from the Nature Publishing Group which started in 2011 with 208 papers, and after 5 years ramping up to nearly 20000 papers in 2018. For whatever reason, the Impact Factor of _Scientific Reports_ is roughly double that of _PLOS ONE_ for around the same article processing charge (APC), drawing far more researchers in. During this same period, since 2013, a great many such examples of 'no impact factor' journals that accept any article that is technically sound began to appear. They are not only the general behemoths like _PLOS ONE_ and _Scientific Reports_, but you will find that even niche journals that make significant numbers of rejections of technically sound papers have their own version that they will offer to you in the same email that informs you of a [rejection](#rejection) from their flagship journal.

The bottom line, from this story of _PLOS ONE_, the highly innovative journal with an attempt to fundamentally change the publishing landscape, is that this is exactly what it did. However, somewhere along the way, the well meaning ideas were hijacked by mainstream publishers' greed. They saw a massive and untapped market. Unsurprisingly, they decided not to call these new entities 'no impact factor' journals, or even the 'rejection pile', but they were binned under the [Open Access](#openaccess) banner.

The bandwagon movement to Open Access that happened as a result of _PLOS ONE_ success, is probably one of the best scams that the publishers have come up with to date. Now the scientists pay for making their own content open for anyone to read. They pay a once off fee to the publishers to typeset the manuscript and host it on their site without a paywall. And how much do the publishers want for this service. Prices start from USD 1000 and go up to around USD 12 000. More frightening, and clear evidence that publishers are simply taking advantage of scientists, is that prices increase with the [Impact Factor](#impactfactor) of the journal [@gray2020sorry], although the costs involved to the publisher remain static. What further evidence do you need?


## So does that mean that OA journals are now free?
Mostly no. The majority OA model ([hybrid OA](#openaccess1)) means that a minority of articles in these journals are free, but the universities are expected to subscribe to those same journals at ever increasing prices because much of the rest of the content is still behind the [paywall](#paywall). This is because most authors cannot afford to pay the exorbitant fees charged by the journals (although some countries now have this payment as mandatory - [cOAlition S](https://www.coalition-s.org/), they and their scientists are still in a minority). There are some journals that are entirely open access ([gold OA](#gold) and [diamond OA](#diamond)). These are (almost) exclusively online and have never been part of traditional packages that university libraries spend so much of their budget on. Hence the fact that they are entirely free does not impact library budgets. The new way to fleece our libraries is through '[transformative publishing agreements](#paywall2)' [@janickehinchliffe2019transformative], estimated to cost up two to three times as much [@poynder2020information].

But paying for open access has not reduced the cost of access to scientific journals for libraries. This cost constantly goes up. [Hybrid OA](#openaccess1) was a brilliant scam dreamt up by the publishers, because for much of this content we pay not twice but thrice [@buranyi2017staggeringly]!

There are people that are trying to stop this constant escalation of publishers wanting money. You, as an Early Career Researcher, are in one of the best positions to do something about this change from [closed to open science](#openscience). Currently, [diamond OA](#diamond) journals are a very small and quite unusual component of the publishing scene. But it is totally possible for these to become the mainstream using initiatives like the [overlay journal](#overlay) system. The current dynamic will only change when academics submitting their manuscripts change from for-profit publishers to other models. The power is literally in your choice of [where to send your manuscript](#whichjournal). 

## Nature Publishing - pay for review
The Nature Publishing Group has now proposed to go one step further: pay to submit your paper for review! In this new twist on the OA scam, the exclusive Nature publishing group is offering a discount to their new USD 11390 OA charge if you pay USD 2665 upfront before review. In this case, you will have the benefit of being told that your manuscript (most likely) is not publishable in Nature, but you can pay some more money to them in order to publish in one of their other journals. The most lowly (Nature Communications) would be another USD 3160, leaving you a few hundred dollars short than if you had submitted there originally. Or you could be rejected outright, and your USD 2665 is, of course, non-refundable. 

- Are Nature Publishing Group taking advantage of authors who aspire to publish in their exclusive titles? __Yes__. 
- Will they use the money to plough back to the benefit of science, scientists and the taxpayer? __No__. 
- Will the cover price of Nature go down when some of the articles inside are free to read? __No__.
- Will it be cheaper for libraries to subscribe to Nature? __No__.
- Will they line their pockets? __Yes__.
- Will they pay the scientists who conduct the peer review that they want to charge for? __No__.
- Can you see the common thread in the greed of publishers and the willingness to prey on scientists who need to publish in high IF journals for their career? __If not, read [Part IV](#part4) again.__

For a lot of academics there is a trade-off: vanity for cash. We know that for a lot of academics, their vanity will mean that they are prepared to find the money (even if it comes from their own pockets). However, for as long as enough are willing to pay, we will continue to be exploited. Instead, we really need a new model for publishing. For some academics they will be paying directly for a chance at [getting a job](#jobinacademia) or [getting tenure](#habilitation). The chances of these individuals reaching their goal from a privileged institution then simply becomes reinforced. 

This is not a system that we should ever support, and one that we should do all we can to remove for the sake of transparency and equality in the greater [scientific project](3beforeyoustart).


**We need a new model for publishing without for-profit publishers**

## The wicked problem {#wicked}

There are growing problems with publishers. Publishing has become very expensive for scientists, and the public who fund science. Many funders are now unwittingly funding publishers instead of science. The history of scientific publishing includes a role for commercial publishers right from the very beginning ([Part IV](#paywall2)). This relationship continues to the present day, but while the origins saw learned societies commissioning publishers and then distributing their content, today the publishers have climbed into the driving seat, conceiving and owning many of the current journal titles. Driving the hiring and promotion of scientists that feed their own products ([Part IV](#badscience)), ultimately leading to [fraud and misconduct](#pruittdata). We, as scientists, have allowed this to happen and we are certainly the people that continue to perpetuate the dominance of for-profit publishers in our scientific domain.

A wicked problem is one that is not only complex, but lacks clarity (with respect to solutions) or a way to scientifically test and study it. According to Rittel and Webber [-@rittel1973dilemmas], there are ten important characteristics, all of which are met by the ongoing situation in academic publishing. There are multiple stakeholders in our wicked problem, and they include our employers, our funders (political and societal), our peers as well as the gatekeepers and societies that police the system. I maintain that there is no solution that will benefit all parties. A practical solution that does not include the for-profit publishers will result in levels of disinformation that will rival those from the oil and tobacco industries. It is up to you to be aware of the options and become part of a solution that benefits science.

As scientists, we need to go back to our core concerns around **the scientific method: rigour, independence, transparency and reproducibility**. We need to persuade our institutions that our core concerns are what we should be measured by, and that the new range of Open Science tools be used to determine the extent to which we live up to our scientific values. Getting jobs, tenure and grants should be based on our Open Science credentials instead of the publishing industry serving [Impact Factor](#impactfactor) and other [publishing metrics](#citations).


### What do publishers do? {#deals}
The publishers would claim that they do an awful lot. All they really do is pay for the layout, printing and distribution of journals. These days ‘printing’ really means hosting electronic pdfs only, as there’s very little paper that’s printed, and you can be sure that paper subscribers now pay the extra cost of any additional fees. The layout from the manuscript (most often a MS Word document) into a pdf does take some skill and talent, although nothing like what you might expect given how much the publishers charge. You can be sure that they don’t pay much for this service as it is almost all outsourced ([cOAlition S](https://www.coalition-s.org/plan_s_principles/) have insisted that OA journals become transparent with their costs). Quality can be good, but more often quality control is completely lacking. Most authors have stories of how manuscripts have come back mangled, although my own impression is that the worst days appear to be over.

This is not to say that there are no skills in the publishing world. But the reality is that these days it is possible to use free software like R Markdown [@xie2018r] to write papers that can quickly and easily be made into any sophisticated layout using LaTeX, the same language used by the publishers. Many journals allow submission of articles already formatted this way.

I also want to make it clear that I am not condemning all those employed by all publishing houses. I have interacted with many excellent staff at publishing houses that have some of the worst practices. It’s important to note that these staff do not get the fiscal benefit of the aggressive and unethical behaviour of their publishing companies. These profits are retained for the directors and shareholders. One might also question whether the sales reps of these companies who make deals with academic libraries don’t also receive unethical bonuses for their undisclosed financial arrangements. But as these deals are not disclosed, who would know or admit this?

### What is publishing then?
Once publishers have ‘printed’ the manuscript, they ‘publish’ it by placing it behind a paywall on their website. I would be the first to admit that there are massive costs in doing this properly, and big journal companies have invested a lot to do this very well. The electronic hosting of journals is (in my opinion) truly excellent, except for that paywall. However, once they’ve set this system up, adding another 10 or 20 journals comes at practically no cost compared to the revenue that each one can be expected to gain.

To get behind that paywall, university libraries need to subscribe. Publishers bundle journals together and sell subscriptions at very high prices. If you are inside the university IP address, this access should be seamless. If you are outside, you might need to log in through your university’s library. There are other tactics for getting around a paywall ([see part IV](#paywall)). 

So far, the publisher hasn’t produced any content. The scientific content has been produced by the scientist at the cost of the public purse. The editing and peer review ([see part IV](#preprint)) has all been done by the scientists, which has also cost the public purse but has been completely free to the publisher. OK, so there are some small costs associated with manuscript handling software subscriptions that the publishers normally pay. The publisher has also paid for the typesetting (although they’ve done this as cheaply as possible - see above), and they’ve paid for the servers that distribute the pdfs maintaining that all important [paywall](#paywall). What else? Nothing else. Now they simply maintain the system, and charge everyone to look at the content (and because it’s by subscription), actually charge everyone whether or not they are looking at the content. Bergstrom and Bergstrom [-@bergstrom2006economics] showed the difference between the costs of subscribing to society journals in 2005 was USD 0.29 while for-profit journals cost US$ 1.42, irrespective of any degree of quality. Fifteen years on, most society journals have now been captured by for-profit publishers, so that now we all pay the higher price.

But don't take my word for it. Read the excellent article by Stephen Buranyi [-@buranyi2017staggeringly]: Is the staggeringly profitable business of scientific publishing bad for science? In it, Buranyi makes the point that the profit margins of academic publishers are in excess of 40%. Something that even drug dealers, pimps and the mafia struggle to achieve. This situation seriously needs to change.

## Making the change {#change}

My message, throughout this book, has been that the tools to make the shift from [closed to open science](#openscience) are available to us now. There is nothing to stop us changing the system other than the need to act collectively. 

[Scholarly societies](#societies) offer an excellent opportunity to organise. Some societies still dictate terms to publishers (for example, [The British Ecological Society](https://www.britishecologicalsociety.org/), and they have the power to finish their contracts and move their journals to new [diamond Access](#diamond) formats, using tools such as [overlay journals](#overlay). In turn, they have to give up the income that their for-profit publishers supply. This does not mean that they would lose all income, they would still have subscription funds and conferences. But there would be a loss of some of the comfort that they have become used to, making giving up hard to do. But societies need to carry out the wish of their members, and I would suggest that there are more members that would benefit from [diamond access](#diamond) society journals, than currently see any benefit in the kick-back from for-profit publishers.
