# Keeping track of your mental health {#mentalhealth}

Stress is a natural part of life, and many people are at their most productive when they are under some degree of pressure, such as a deadline. Although deadlines don’t work for everyone. Problems arise when we become overwhelmed by stress and are unable to fully respond. When this occurs productivity can drop off and survival responses can be triggered as if responding to an actual physical attack. These responses include fight, flight or freeze responses. Anxiety and panic can be triggered. In this state additional demands on your time may also push your life off balance, so that you start to neglect your personal wellbeing which can negatively impact on relationships, exercise regime, or even nutrition and personal hygiene. Some people can find that the additional stress can cause physical symptoms that may even need medical treatment. Your sense of competence and mastery can be negatively impacted such that you may even suffer from feelings of inadequacy or imposter syndrome. Impostor syndrome is an experience you have when you believe that you are not as competent as you think others perceive you to be. It is not uncommon in many professions, and especially prevalent in academia [@clance1978imposter]. This is now widely recognised and there are lots of useful shared experience out there to read [e.g. @dickerson2019how].

The General Health Questionnaire is an instrument used to measure psychological distress. For example, you could use the GHQ-12 in [Table 4.1](http://www.howtowriteaphd.org/healthy.html#tab:GHQ) [see @measey2021how]. It is quick, reliable and simple to score, so you can use it at any time during your career as an indicator of whether you need to reach out to personal, occupational or professional support networks. My suggestion is that you complete a General Health Questionnaire now and record your answers as a baseline. Keep the scores somewhere safe. If you feel that you are getting overly stressed, take the test again and compare them with your baseline scores. Although there are no hard rules, if three or more of your scores have moved by two or more points it could be worth discussing with your support network to help you decide whether or not to seek professional help.  

Even if you don't feel you need the support of your institution now, it is worth finding out how they can support your mental health in the future if needed. Although there has been some stigma attached to difficulties with mental health in the past, most institutions accept that pressures are mounting on their staff and that they may require support. Most institutions will make experienced councillors available to support you if needed. Importantly, you should realise that none of these symptoms are unusual and that there is a high probability that many of your colleagues may also be struggling. Knowing that your problems are shared and reaching out to support networks early is an excellent way to prevent them from escalating beyond your control. Your best means of coping will be to try and develop a support network and to understand where and with whom you can discuss any difficulties as they arise. Knowing who this is and how and when to approach them will put you in a stronger position if you need them in future.

## Being physically active improves mental wellbeing

The positive relationship between the amount of physical activity and higher mental wellbeing is well established [e.g. @grasdalsmoen2020physical; @gerber2014increased], but the kind of exercise required to achieve this improved result is varied. There are plenty of studies out there that suggest there are multiple benefits from physical activity [@williams2021move]. This does not have to be the most hectic exercise possible. You'll get huge benefits from simply taking a walk.

This does not exclude you from participating in other less physical activities, including mindfulness or meditation. Try different types of activities and then do what's right for you.

## Time to think

Use the time that you spend exercising as thinking time: turn ideas over in your head, think through the logic in arguments, and potential flaws in experimental design. If you can, spend this moving time with others in your group discussing projects and talking about ideas. There are reasons why we do some of our best thinking when physically active, and you should seek to exploit these when you can. For example, if you have a meeting scheduled then why not do it as a walk - even if it's on the university campus this walk will get you and your colleague in a much better space to plan ideas. 

This isn’t to say that you won’t need time at the computer writing it all down, or talking around a table with colleagues. Be inventive in how you spend your time, and don't resign yourself to spending all day sitting behind a desk. Don’t take my word for it, see this great new book by Caroline Williams [-@williams2021move].
