# Getting a job inside academia {#jobinacademia}

I have already written at the start of this book (see part 1) that competition is high to get jobs in academia and your chances are therefore diminishing. However, academia needs new academics, and so I wanted to try to provide some key insights into what might be important in getting a job as an academic. Of course, there is no single way in, and your path is likely to be different to mine and others that you meet.

During lockdown in 2020 my lab held some meetings with invited guests from all over the world. What follows is a list of key insights that came from a meeting with four academics on four continents. if you are interested in getting a job in academia then take a look and consider these. 

## Key Insights if you want a career in academia
Here is a list of key insights that our team shared. They are in no particular order, but each one probably deserves a lot more information. 

- Academics often suffer from [imposter syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome)
- A suite of skills that are all are required:
  + Need a logical mind: even OCD
  + Good writing skills
  + Computational skills
  + Attention to detail
  + The importance of finishing the job
  + Being creative (not just for arts students)
  + Need to read (a lot)
- The coolest job in the world as you’re paid to learn
- Research has to be fun 
  + Once you have a tenured position metrics are unimportant to you (but remain important to your students!)
  + Have to produce a publication that you are proud of
- You have to tolerate rejections
  + Papers
  + Conferences
  + Positions
  + Promotions 
- Don’t be harsh on yourself - it happens to everyone
- Don’t rely on how people used to get hired, or that positions you see now will become available in the future 
- Don’t ignore the importance of natural history observations
  + Write the notes as they demonstrate productivity
  + They make your CV look stronger in the early stages
  + Use them to get things published strategically
  + Don’t fill your CV exclusively with these notes (there are more important things)
- There is still a glass ceiling in employment institutions
  + Things are improving
  + Don’t allow comments phase you - many people don’t understand their own prejudices or discriminations.
  + Share the down sides, you’ll find out that lots of other people experience them, and not just you
- Role models are very useful in science
  + Especially someone with whom you can identify, preferably from your own background
  + Use your network to explore which role model might fit best
- Someone needs to fit into the context of the job
  + This means that not every job will be right for you as other people might fit better [not the fault of you or your CV]
  + Could be why lots of people get jobs from the inside - they are already known to fit into the team
  + Many institutions pride themselves on their position in the community, and will look fondly on people who are clearly committed to the place. This could include:
  ++ Speaking the local language
  ++ Writing popular articles for a local audience
  ++ Engaging with the local press and media
  ++ Giving talks to local groups
  + Give back into the faculty or institute - can you demonstrate that you do more than just conduct research and write papers. Are you active in your community (both big - academic community and small - departmental community)
- Learn about opportunities and take advantage of them [you make your own luck]
  + Many people don’t know about opportunities that are out there. 
  + Meet people one on one at smaller meetings [big meetings aren’t good for this]
- Moving around [in postdocs or between jobs] can make it more difficult to get accepted into some places that have a culture of staying put
  + If you know where you want to be, it’s worth investing time to that institution and community [but don’t count on it!]
  + Try to keep multiple irons in the fire
- Even though career paths look linear, this is really only in hindsight. In reality they are wondering paths that sometimes wonder right out and back in again
- Writing small grants isn’t a waste of time as it develops this as a skill 
  + Grant writing is different to thesis writing or paper writing
  + Having a CV with evidence of lots of grants gained (even if they are small) demonstrates to people that you know this stage of the process
  + Showing that you can finish the same projects and produce outputs is even better
- Try saying yes to opportunities (especially early on in your career)
  + You never know where it will take you
  + Establish collaborations outside your direct circle
- Creativity includes reinventing yourself and your science as you move through your career
  + Each grant proposal is to do different work and take you into new paths and directions
  + Some will work out and open up whole new areas or specialities. Others won’t
- It’s easier if you can describe exactly what you do early on in your career
  + A very mixed up CV leaves some people unclear about who they are hiring and for what
  + This doesn’t mean that you have to be overly focussed, but early on it’s useful to have a tag (or a few specific categories like “systematics”, “comparative anatomy”, “natural history” to organize your publications if they’re really different from each other)
- What type of job do you want?
  + Teaching - then get teaching experience 
  + Research - then make sure your CV is strong
  + There are more types of jobs out there, but if you know what you want (or don’t want) then make sure that your CV reflects this
- Your first job is not necessarily your last job 
  + But it could be if you love it
  + You can use it as a springboard to go elsewhere
  + You might need to take the first job to get somewhere else
- Learn about what you are good at and embrace it
  + This might require some honest reflection
- It’s totally possible to have a job outside academia and then move back in
  + Some jobs might even give you an advantage in getting an academic position
  + Many academic subjects are applied, and so experience in the relevant jobs really help [industry relevant experience]
  ++ You may then have inside knowledge to subjects that are taught
  + Maintain your understanding of the field (to get back in)
  + Make sure that there is a continuing narrative, a reason why you left and why this helps you come back in 
- Keep irrelevant jobs off your CV
- Knowing what you don’t want to do can be as helpful as knowing what you do want to do
  + Internships are great opportunities for this
- Get feedback on the letters that you write when applying for jobs
  + Ask people whether they will give you a letter of reference, and if that will be positive 
  + Take note of what the job is asking for and ask specifically for those aspects to be mentioned
  + Different regions of the world have different styles for letters of reference
  ++ US letters are thorough [and often over the top, even flamboyant] and very long
  ++ Europeans tend to be understated and more direct
  ++ Some parts of the world may provide just a few sentences
  + I ask students to draft their own letters that accentuate what they themselves want to underline about their experiences. I won’t use the same words, but it will help remind and inform me of what colleagues have done.
