# Leaving academia for a job outside {#leavingacademia}
 
In addition to thinking about jobs inside academia we also invited some past members of my lab who have got jobs outside of academia. They also provided us with their key insights into how the world outside academia is different to that inside. Again, if you are thinking about it getting a job outside academia take a look at some of these key insights.


## Key Insights if you are looking for a career outside academia
- The importance of the networks that they had made during their times as academics. In addition, the importance of how to manage and grow a network. 
- Many jobs these days involve project work, and include generating the funding from donors as well as completing the project and writing the report. Post graduate degrees really help with learning how to start, manage, and complete projects.
- Although papers and citations gained during academic life won’t help with some jobs, they allow flexibility in the job market (potentially to re-join academia). They also demonstrate your ability to write. More papers are likely to improve your chances and some jobs include writing research papers as part of the job.
- Employers are interested in the experience and skills that you’ve acquired during your academic work. Instead of just listing papers you need to sell what you’ve done in cover letters and interviews:
  + What kind of experience do you have with your specialist area?
  + Do you understand about management?
  + Do you have good organisational skills?
  + Have you done fieldwork?
  + Have you managed students?
- Regardless of your academic background, you should expect to enter into your job at quite a junior level or even as an intern, and then work your way up
- Employers are looking for ‘emotional intelligence’ (the ability to understand and manage your own emotions, and those of the people around you). They will expect you to be a good team member, work with different stakeholders and clients. Conflict management skills are important. 
- You might not need to wait for a job advert. Use your contacts and write to people who are employers
- You might need to become ‘comfortable with feeling uncomfortable’: your work might be so different from what you’ve done before that you should and you should be able to adapt
- There are expectations from employers that you will meet challenges that your employers place before you (and not shy away)
  + Pay special attention to the Key Performance Areas (KPAs) of the position you apply for. These are what you will need to report on in order to have your performance in your job assessed.
- You might need to get used to different working cultures that are meeting focussed (even when you have meetings about having meetings)
- The working culture might not be static, and could change with the replacement of a manager or director.
- If you are employed by a governmental agency, it will be expected that you are accountable to your employers as well as the public that pays through their taxes
- The position you are employed in will likely involve you constantly acquiring new skills, such that you feel like more of a student then when you were studying. This really adds to the interest in the working life, and allows you to meet new and unexpected challenges.
- New subjects and other areas might be well outside your expertise, but can be just as rewarding once you rise to meet the challenges. 
- Jobs outside academia are especially challenging in working out how to apply the results of scientific studies. 
- Your employers might expect you to conceive your projects, as well as carrying them out.
- You are expected to be an authority in your work, and interpret your results in context and with reasonable confidence

At the end of the day, you need to discuss what you want and what you expect from your job outside academia with as many people as possible in that profession. 
