--- 
title: 'How to write a PhD in Biological Sciences: a guide for the uninitiated'
author: "John Measey"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
site: bookdown::bookdown_site
description: You don’t have to be a genius to write a PhD. It will always involve
  a lot of hard work and dedication, but the process of writing up is a whole lot
  easier if you understand the basic ground rules. This book is a guide specifically
  for writing a PhD in the *biological sciences*. It will guide you from deciding
  whether or not you should actually do a PhD, provide practical, up-to-the-minute
  guides to getting started with planning and writing, and consolidate this with the
  nuts and bolts of writing for the biological sciences. The book guides you through
  the do’s and don’ts of writing a thesis, and taking your thesis chapters to publication
  in peer-reviewed journals. Whether you are a student just starting your studies,
  or a supervisor struggling to cope, this book will provide the insider information
  you need to get ahead.
github-repo: yihui/bookdown-crc
graphics: yes
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# install the packages needed by this book; you fill out c(), e.g. c('ggplot2', 'dplyr')
lapply(c('xfun'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```


# Welcome {-}
Welcome to this guide on how to write a PhD in biological sciences. I will not tell you what to write. My intention is to tell you how to approach writing with respect to style, format and formula (planning). 

Writing a PhD is a daunting prospect. One does not put pen to paper, or, rather, finger to keyboard, only after finishing all of your experiments and/or labwork. Writing is actually something you should start from day one of your PhD, or even before day one, when you make the first initial pitch of big ideas to your advisor on what you want to do. If you can find the discipline to start writing from day one, then you are much more likely to make a much better go of it than waiting until the final, pressured, stretch. But to do this, you need to understand how to write a PhD thesis. You need to understand what you are aiming to achieve, and, crucially, you need to understand why you are doing your PhD. 

This guide intends to demystify the writing process so that the eventual goal is clear, and provide the necessary information on how to get there. It takes you from those initial ideas, all the way through proposal writing, posing hypotheses, testing them, and then how to write it all up.

This book started as a series of blog posts written by me for my students (john.measey.com/blog). I wrote them because I felt that I was repeating the same advice year after year. Instead of rewriting comments on manuscripts time after time, I thought I would consolidate them and put them all in one place. Later, I started looking for particular problems that students were having, and then writing blog posts to try to preempt those problems, and to provide solutions before tasks were completed. Finally, I have tried to fill in the missing gaps in the blog posts. But there are still plenty of gaps, and I regard this book as a work-in-progress. It is my intention that this book will always be added to, and improved by a community of practice, and I hope that this will include you.

## Why read this book {-}

Embarking on a PhD is intimidating as, for most students, it will be their first experience working within the academic system. The voyage of discovery is often made very frustrating as much of what goes on in academia is assumed knowledge. Academics accumulate knowledge throughout their careers, but what can be done for those who are uninitiated? What is needed is a guide. In the same way that we had guides to foreign countries and cities, postgraduate students need a guide that newcomers can refer to before, during and when making decisions about their time within academia. Note that this is not a rulebook. There are times when the guide will be accurate and others when it will be vague, but providing some insight to point you in directions where you can explore more. 

## Structure of the book {-}

This book is intended to be a guide. Don't sit down and read it from cover to cover. If you do, then I think you have likely misunderstood what this guide is for. Instead, I want you to think about this book as a guide much in the same way that you might pick up a guide to a foreign city, country or even like Douglas Adams' fabled electronic guide _The Hitchhiker's Guide to the Galaxy_ @adams2017ultimate (if you are not familiar [see here](https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy)). However, instead of having hostels or restaurants recommended by name with a description of what makes them particularly praiseworthy, this guide provides a generic idea of what such places are for, what they tend to be like, the best ways to get to them, and pitfalls to avoid. 

None of the topics is explored in any great depth. This is deliberate as this guide is here to provide you with a starting point for you to explore if you think it is necessary. I have provided literature (where possible), and you should use this in the standard way to research the topic yourself should you need or want to know any more. In the same way, none of the advice provided in this book should override what you decide for yourself or with your advisor. Take your decisions from an informed position. 

**The book is divided into four main parts:**

[**Part 1**](part1.html)
Part one is written as something that you should read early on in the process, once you’ve committed to doing a PhD. This shortest section of the book deals with what a PhD is, how it’s examined, with whom, where and when to do it. At the start of your PhD is the time to be thinking of the bigger questions both in your study area, and your life, and this section provides some pointers and things to consider.

[**Part 2**](part2.html)
Part two of the book sets out a practical guide to getting started with writing. The approach I've taken here is describing the production of a PhD in biological sciences which is made up of data chapters, and where each chapter is essentially a potential publication in a science journal. If you didn't want to do a PhD but just wanted to write a publication, then most of what is here (and in [Part 3](part3.html)) will be of use as you could take the same formulaic approach as given in this book. Similarly, if you were writing a MSc project, this section would also be useful. There is a lot of technical stuff involved in writing science, and in part 2 I cover as much as I can while still remaining general to the subject area.

[**Part 3**](part3.html)
A typical PhD will consist of five data chapters where each data chapter is a publication. There is a shortish introductory chapter (sometimes a literature review) that comes before these data chapters, and a concluding synthesis chapter at the end. That's not to say that this is the only way of writing a PhD. There are many different ways and it is a good idea for you and your advisor to talk about this together before you start. 

This part covers how to write the core sections of a paper: abstract, introduction, methods and materials, results, discussion and references. 

[**Part 4**](part4.html)
The concluding part of this book is written to cover the things that remain after you have finished writing all of your data chapters. Most importantly, these include the introductory and concluding chapters that sit as bookends to the data chapters that you have already produced. These chapters make your thesis into a 'body of work', and allow you space to reflect on what you have achieved in your PhD studies.

Throughout this guide you will find links and references of things to read elsewhere. The reality is that there is a lot out there for you to read. I am not the only person to write a guide, and I can't pretend that all the answers are here in this book. You will find that in your particular situation you need to look around. What I aim to do in this book is provide you with enough background information to help in your onward search, and provide you with enough inside knowledge to do a PhD. 

## Why 'A guide for the uninitiated'? {-}

I think that most people with doctorates would agree that a PhD is not awarded to people because they are particularly bright or smart. If you had to be a genius then I wouldn't have a PhD. Indeed, I don't consider myself to be particularly clever, but I worked very hard to get my PhD. I was hampered by the fact that I didn't know anything about the goals and aims of the academic process of working towards a PhD, so it took a lot more work, wasted time, and (let's not mince our words) real pain. The end product was a fraction of the potential that I could have achieved, if I had understood more about the process. If I had only had a guide to tell me what it was all about, I could have saved myself so much time and energy. In short, I feel that I was uninitiated, and this is the guide I wish that I had had.

So, this guide is my practical attempt to help you to get the most that you can out of your PhD time. After all, it should be an amazing journey that culminates with you achieving academic maturity: the ability to conceive and carry out scientific investigations. When you have a PhD, you become a scientist. Too often, however, it's a nightmare journey of cul-de-sacs, and groping in the dark. 

You should be aware from the outset that doing a PhD is a major undertaking. It will take several years of your life and will impact heavily on your day to day life, to the extent that your mental health may suffer. A PhD represents the culmination of an incredible amount of work, not to mention that you've already had to complete one to three previous degrees beforehand. It may not be something that you ever finish to your own satisfaction. But finish it you must.


## Acknowledgments {-}

Before I go on, there are a great many people that I need to thank. First and foremost are my students, past and present, who have inspired me to put together first the blog posts and then the book. It is because you wanted more that I put this together. I have also been a student, and have been inspired by colleagues around the world who have been exemplary advisors. This book contains lots of links to blogs and articles written and posted freely on the internet by others who also aim to demystify and help. I thank this greater academic community for sharing and inspiring. Thanks go to the many reviewers and editors who have taken their time to improve my writing. I am still learning. Lots of the text in this book has been improved by feedback from my students and postdocs. A special mention must go to my brother, Richard, who has hosted my lab website for more than a decade, and especially for saving blog posts from hacking attacks. Thanks also to my wife, Thalassa, who proofread many of the blog posts after I had published them late at night, so that I could correct them over breakfast in the morning. James Baxter-Gilbert, Anthony Herrel,  Lisa O'Connell, Mark O'Connell, James Vonesh all read parts and commented. Thanks are also due to my colleagues at the Centre for Invasion Biology, the Department of Botany and Zoology, and Stellenbosch University. A special thanks to the librarians who have supported many of my more extreme rantings about publishers.

```{block2, type='flushright', html.tag='p'}
John Measey  
Cape Town
```

